### PR TITLE
Obey GTEST_FLAGFILE; fixes #1262

### LINKED ISSUE #1262: GTEST_FLAGFILE is ignored
GTEST_FLAGFILE ought to be obeyed, but is ignored because it is never checked
unless --gtest_flagfile is given, which overrides its value.

### PR DESCRIPTION
**Pull request by dankegel**

### CODE REVIEW

**Comment by gennadiycivil** [comment]
@dankegel , thank you for your contribution. Could you please explain how GTEST_FLAGFILE should work. I am not able to find exact documentation . What did you base your statement in #1262 that "GTEST_FLAGFILE ought to be obeyed" on?
Thank you again

**Comment by gennadiycivil** [comment]
@dankegel ping pls

**Comment by dankegel** [comment]
I'll reply when I get a moment, thanks

**Comment by gennadiycivil** [comment]
@dankegel ping

**Comment by gennadiycivil** [comment]
No response, seems abandoned

**Comment by dankegel** [comment]
See https://github.com/google/googletest/pull/2727

**Pull request closed without merging**
