### PR TITLE
README.dm: Renamed open source project 

### PR DESCRIPTION
**Pull request by matepek**
Renamed related open source project name: Catch2 and Google Test Explorer -> C++ TestMate

### CODE REVIEW

**Comment by matepek** [comment]
@googlebot I fixed it.

**Comment by matepek** [comment]
@googlebot I fixed it.

**Comment by matepek** [comment]
Can I get some help? What am I doing wrong here for **cla**?

Screen Shot 2020-05-10 at 07 14 19

**Comment by matepek** [comment]
@googlebot I fixed it.

(Tried to accept today too.)

**Comment by asoffer** [comment]
It looks like we have a CLA associated with your github username (matepek) but not with the email address associated with the PR (mate.pek@agoda.com). Perhaps they're not linked in your account?

**Comment by matepek** [comment]
Ah okay, I understand the problem. Thank You @asoffer . Please delete your comment because of the PI. ^^

**Comment by asoffer** [comment]
Comment deleted (sorry!) And all looks good. Pulling this in now.

**Pull request merged**
