### PR TITLE
Use std::forward instead of std::move for MockFunction

### PR DESCRIPTION
**Pull request by marbub**
If you use std::move you get an compile error for MockFunction<void(Foo&)>.

### CODE REVIEW

**Comment by gennadiycivil** [comment]
@marbub Thank you for this contribution. This looks mostly good, however could you please re-implement this in the pump file. As specified in the beginning of the file this file is generated.
Thank you again

**Comment by gennadiycivil** [comment]
> forward<A$j> ?

yes!
Thank you

**Comment by marbub** [comment]
Your welcome :-)

**Comment by gennadiycivil** [comment]
@marbub Could you please provide test run before and after with output showing the successful results

**Comment by marbub** [comment]
@gennadiycivil I don't understand? Which test run? My tests?

**Comment by gennadiycivil** [comment]
@marbub So there was a piece of code that used to not compile as you mentioned in #1868 . Now that this you put together this change this piece of code works.. 

The easiest approach to show the "success" is to make a unit test out of that code. I recommend adding this new Unit test to googlemock/test/gmock-generated-function-mockers_test.cc.

Thank you again
G

**Comment by marbub** [comment]
I messed it up. I simply have no experience this github. ;-(

**Comment by marbub** [comment]
I feel really sorry, the workflow feels really different from gerrit. Thank you for your help!

**Pull request closed without merging**
