### PR TITLE
Add support for "noexcept" specifier in MOCK_METHOD... macros.

### PR DESCRIPTION
**Pull request by goofacz**
I implemented "noexcept" function specifier in MOCK_METHOD... macros. Solution for issue #667.

### CODE REVIEW

**Comment by BillyDonahue** [comment]
We're looking for a solution that won't have a combinatoric problem if
other annotations need to be added to the method, like override or
ref-qualifiers (& or &&).

**Comment by goofacz** [comment]
You're right. The idea behind my changes was to provide consequent interface (we have MOCK_METHODn, so we should have MOCK_NOEXCEPT_METHODn etc.). I was aware it opens doors for combinatoric problem.

What about giving users freedom of setting  function specifiers? You can introduce 
MOCK_METHODn_WITH_SPECIFIERS(method, specifiers, ...)? Then MOCK_METHODn and MOCK_CONST_METHODn can be reimplemented on top of MOCK_METHODn_WITH_SPECIFIERS without breaking API. 

Embedding specifier in macros' names closes possibility of extending them in future (maybe we will see new specifier in e.g. C++21?).

**Comment by Bagira80** [comment]
A more general solution, which supports several combinations of function-qualifiers, was originally provided in issue #546.
The original patches do no longer apply cleanly, but I sorted the problems out and fixed them.
These changes are provided in pull-request #794.

However, for supporting functions with rvalue-references (`&&`) as parameters some additional internals of GoogleMock need to be adjusted, I assume.

Just so that you know:
We have been using these patches in our company for several years now and they worked well.

**Comment by gennadiycivil** [comment]
No CLA, closing

**Pull request closed without merging**
