### PR TITLE
Use `$<INSTALL_PREFIX>` in `target_include_directories`

### LINKED ISSUE #1764: CMake Errors in googlemock
### description
At commit  880896c the recommended method of including googletest in your project results in cmake errors (see below). I have reproduced this error on FreeBSD 11.2 (cmake 3.12.<something>), Ubuntu 16.04 (cmake 3.5.1), and Ubuntu 18.04 (cmake 3.10.2). 

### fix
Changing cmake to require commit b88511e rather than `master` seems resolve the issue.

```
ExternalProject_Add(googletest
  GIT_REPOSITORY    https://github.com/google/googletest.git
  GIT_TAG           b88511ef640c046ec9c7553b383a2aba64c80967
  SOURCE_DIR        "${CMAKE_BINARY_DIR}/googletest-src"
  BINARY_DIR        "${CMAKE_BINARY_DIR}/googletest-build"
  CONFIGURE_COMMAND ""
  BUILD_COMMAND     ""
  INSTALL_COMMAND   ""
  TEST_COMMAND      ""
)
```

### symptom
```
CMake Error in build/googletest-src/googlemock/CMakeLists.txt:
  Target "gmock_main" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "[...]/build/googletest-src/googletest/include"

  which is prefixed in the build directory.


CMake Error in build/googletest-src/googlemock/CMakeLists.txt:
  Target "gmock_main" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "[...]/build/googletest-src/googletest/include"

  which is prefixed in the build directory.Target "gmock_main"
  INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "[...]/build/googletest-src/googletest/include"

  which is prefixed in the source directory.


CMake Error in build/googletest-src/googlemock/CMakeLists.txt:
  Target "gmock_main" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "[...]/build/googletest-src/googlemock/include"

  which is prefixed in the build directory.


CMake Error in build/googletest-src/googlemock/CMakeLists.txt:
  Target "gmock_main" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "[...]/build/googletest-src/googlemock/include"

  which is prefixed in the build directory.Target "gmock_main"
  INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "[...]/build/googletest-src/googlemock/include"

  which is prefixed in the source directory.
```

### PR DESCRIPTION
**Pull request by dakotahawkins**
To make sure packages are relocatable, use `$<INSTALL_PREFIX>` in `$<INSTALL_INTERFACE:...>` `target_include_directories`.

`$<INSTALL_PREFIX>` was introduced in CMake 2.8.11, which is already being checked for locally.

References:

- https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#id19
- https://github.com/robotology/how-to-export-cpp-library/blob/claudio/headeronly/src/LibTemplateCMake/CMakeLists.txt#L42

Signed-off-by: Dakota Hawkins <dakotahawkins@gmail.com>

### CODE REVIEW

**Comment by dakotahawkins** [comment]
Since I can't reproduce this myself for some reason, I'd like @wfvining to confirm this fixes their issue. It's definitely a problem I've had before writing CMake for other projects, I just can't remember how to have that same problem at the moment...

**Comment by gennadiycivil** [comment]
@wfvining pls confirm?
Thanks

**Comment by dakotahawkins** [comment]
@gennadiycivil If it somehow doesn't fix the problem, I think it's still supposed to be this way (using `$<INSTALL_PREFIX>`). In that case I'll rewrite the commit message to remove "Fixes #1764".

**Comment by dakotahawkins** [comment]
@gennadiycivil Looks like #1764 isn't related to this. I've updated the commit message, PR title and description.

**Pull request merged**
