### PR TITLE
Wrong version reported (1.7.0 should be 1.8.0)

### PR DESCRIPTION
**Pull request by zeitounator**
`gtest-config --version` reports wrong version.

Correction made against master branch but please note that this affects tag release-1.8.0 and the distribution tarballs.

### CODE REVIEW

**Comment by KindDragon** [comment]
That version should be probably changed too:
https://github.com/zeitounator/googletest/blob/fa892afcb9532fe559a067b49f31952c7a80c3c7/googlemock/configure.ac#L4
https://github.com/zeitounator/googletest/blob/fa892afcb9532fe559a067b49f31952c7a80c3c7/googlemock/configure.ac#L104

**Comment by zeitounator** [comment]
Thats right. I was focused on googletest since the project I compiled does not use googlemock. Just made the update on the branch.

**Comment by gennadiycivil** [comment]
Both AppVeyor and Travis Builds failed. This should not happen of course, could you please re-trigger them and see what happens

**Comment by KindDragon** [comment]
> This should not happen of course, could you please re-trigger them and see what happens

Just reopen PR to rebuild it

**Comment by zeitounator** [comment]
Hey cool :)

**Pull request merged**
