### PR TITLE
Fix mingw build

### PR DESCRIPTION
**Pull request by graywolf**
CMAKE_USE_PTHREADS_INIT on itself is not enough to correctly compile
on mingw, changed to CMAKE_USE_PTHREADS_INIT AND NOT MINGW.

### CODE REVIEW

**Comment by graywolf** [comment]
Signed.

**Comment by KindDragon** [comment]
It shouldn't be defined because of that: https://github.com/google/googletest/blob/48ee8e98abc950abd8541e15550b18f8f6cfb3a9/googletest/cmake/internal_utils.cmake#L51-L54

**Comment by graywolf** [comment]
But in it's current form it's very sensitive to order in which you `add_subdirectory`.. for example, in my case `find_package(Boost)` before `add_subdirectory(googletest)` cause build to fail because `googletest` had `CMAKE_USE_PTHREADS_INIT` already set to 1.

**Comment by gennadiycivil** [comment]
I see a failed AppVeyor build, which may or may not be related. I am going to close it and re-open to trigger another build

**Comment by gennadiycivil** [comment]
This is sadly out of date now and there are merge conflicts. 
Best way forward is for me to close it. Please feel free to re-open, resolve the merge conflicts and we could take a look

**Comment by graywolf** [comment]
I'm not sure how to reopen this. I only have "Comment" button under this text area. However I've updated https://github.com/graywolf/googletest/commits/fix_mingw by merging master into it. Could you try now?

**Comment by gennadiycivil** [comment]
Reopened, lets get the clean build

**Comment by gennadiycivil** [comment]
We now have functioning MingW build, see #870 , I am closing this as duplicate, please tell me otherwise

**Comment by graywolf** [comment]
I don't think this is a duplicate of #870. This PR is not so much about googletest not building at more and more about it being sensitive to order in which are `add_subdirectory` in `CMakeLists.txt` done. Please see my comment in response to KindDragon on Mar 1. For more details. I looked into diff for #870 and I don't think it fixes this particular issue.

**Pull request closed without merging**
