### PR TITLE
Update example to reflect the tests below

### PR DESCRIPTION
**Pull request by ramkumar-kr**

### CODE REVIEW

**Comment by asoffer** [comment]
We're happy to merge this, once the CLA is signed.

**Comment by ramkumar-kr** [comment]
Hi,
I have signed the CLA.

**Comment by asoffer** [comment]
@ramkumar-kr, I still don't see the CLA merged.

**Comment by ramkumar-kr** [comment]
Hi,
The dashboard for me shows that I have signed the CLA... Here's a screenshot of the page -
image

Please let me know if anything else is missing from my end.

Regards,

**Comment by asoffer** [comment]
Thanks, it seems like the icon was just stale. Merging now.

**Pull request merged**
