### PR TITLE
Remove a custom implementation of std::enable_if

### PR DESCRIPTION
**Pull request by kuzkry**
#2392

### CODE REVIEW

**Comment by asoffer** [comment]
263426328

**Comment by EricWF** [comment]
This LGTM. 

Although, it's fun to point out that this could change the behavior of code, because it's possible to observe the difference between `enable_if<false>` being an incomplete type as opposed to a complete type with an empty definition.
But anybody clever enough to do that is clever enough to fix it.

**Comment by kuzkry** [comment]
Heh, right! But look, no fixes needed; incompilable code is still incompilable :)

**Comment by kuzkry** [comment]
Merged by 9bf34ace.

**Pull request closed without merging**
