### PR TITLE
fix build break on locale windows

### PR DESCRIPTION
**Pull request by fo40225**
fix build break on locale windows

### CODE REVIEW

**Comment by gennadiycivil** [comment]
@fo40225 Thank you for your contribution. Could you please verify and confirm that you are the author of all commits in this PR and that you are OK with this being merged.

**Comment by fo40225** [comment]
Yes, I am the author of all commits in this PR.

**Comment by gennadiycivil** [comment]
@fo40225 ... and are you OK with the commits in this PR being merged into googletest? Thanks again, I have to get your explicit consent

**Comment by fo40225** [comment]
I am OK with the commits in this PR being merged into googletest.

**Pull request merged**
