### PR TITLE
Prevent infinite loops for recursive containers like boost::filesystem::path

### PR DESCRIPTION
**Pull request by Dani-Hub**
This pull request introduces an additional detection for recursively defined containers (such as ``boost::filesystem::path`` or ``std::filesystem::path``) and prevents the possibility of an infinite loop within the output handler for containers.

### CODE REVIEW

**Comment by Dani-Hub** [comment]
I signed the CLA.

**Comment by gennadiycivil** [comment]
Please add tests so we have evidence that this in fact works as intended

**Comment by Dani-Hub** [comment]
Can you give me a hint about the test guidelines in googletest? First: Where should these be added? Is it expected to add tests to both googletest and googlemock? Thanks.

**Comment by Dani-Hub** [comment]
I looked into the existing googletest test directory and found that gtest-printers_test.cc is already the right test for this. I will add a corresponding test case to this pre-existing test file.

**Comment by Dani-Hub** [comment]
I signed the CLA.

**Comment by Dani-Hub** [comment]
Is there anything that I need to do to realize that the CI build will run again?

**Comment by Dani-Hub** [comment]
Could someone please review the suggested patch? Thank you!

**Comment by gennadiycivil** [comment]
Note that appVeyor build failed , could you please take a look what happened

**Comment by Dani-Hub** [comment]
Yep, I'll fix it this evening.

**Comment by Dani-Hub** [comment]
Note that the fixed had been applied and the previous build succeeded. I decided to update the branch yesterday (This IC is still in progress), but that seems to be an endless story, so I don't intend to apply further changes and instead await the review approval.

**Comment by gennadiycivil** [comment]
Thank you for the updates. I fully support small PRs that are much easier to handle. For this PR, could you please add full test information as well as the test output before/after to demonstrate what we are fixing and how works now. Thank you

**Comment by Dani-Hub** [comment]
I'm not sure that I understand your request, but the set of changes are intended to solve the problem described in issue #521. Does this clarify your question?

**Comment by gennadiycivil** [comment]
Yes, this has information needed. 
We just need testing evidence, test *before* this PR and demonstrate the problem in action ... and after that test again "after* this PR to demonstrate that solution works

**Comment by Dani-Hub** [comment]
The real-world test will require someone to validate that `boost::filesystem::path` and `std::filesystem::path` will cause normal output by the gtest printers, but I cannot make gtest itself dependent on these concrete types, therefore these types are not used in the test. The patch will work for every "recursive" container and that is validated by the added test in `gtest-printers_test.cc` by means of the most minimal recursive container example denoted as `PathLike`.

**Comment by gennadiycivil** [comment]
How about using Alexhuszagh's Jun 19 suggestion (<experimental/filesytem>) ? 
We do need a real world test. The best would be adding a new unit test, with appropriate ifdefs to protect against old compilers

**Comment by Dani-Hub** [comment]
No, `<experimental/filesystem>` is not a required header, so we cannot rely on the assumption that it is available. I don't understand the difference between the test type and a "real-world" type. I'm not willing to re-implement std::filesystem within a test just as a proof for *another* possible type in the world that behaves correctly similar to `PathLike`. What is wrong with `PathLike` alone?

**Comment by SimonEbner** [comment]
PR fixed the issue nlohmann/json#709

**Comment by gennadiycivil** [comment]
Thank you for detailed explanation. lgtm

**Pull request merged**
