### PR TITLE
Small sys/-related changes

### PR DESCRIPTION
**Pull request by kuzkry**
Small clean-up, which I didn't want to make a part of another pull request.

### CODE REVIEW

**Comment by luispure** [comment]
What's going on

**Comment by kuzkry** [comment]
What do you mean? Did I do sth not right?

**Comment by luispure** [comment]
Hey not all good quick question I wanna get into developing I wanna make
apps and stuff like that do you know what courses should I take or what
should I do thank you if you can help me thanks a lot

**Comment by luispure** [comment]
If u Wanna leave you personal email I can really send you a email with my
other email I'll really appreciate it  thanks a lot

**Comment by kuzkry** [comment]
Is this April Fool's prank? If no, look it up on the Internet; I can't advise you better because I don't know you.
Anyway, please don't clutter PRs with unrelated questions.

**Comment by vslashg** [comment]
Our reading of the man page is that the second argument of sysctl is of type u_int.  (https://www.freebsd.org/cgi/man.cgi?sysctl(3))  We believe this code is correct as is.

**Comment by kuzkry** [comment]
Oh, you're right!

**Pull request closed without merging**
