### PR TITLE
README.md formating fixed

### PR DESCRIPTION
**Pull request by KindDragon**
[Preview](https://github.com/KindDragon/googletest/blob/master/README.md)

### CODE REVIEW

**Comment by KindDragon** [comment]
BTW, IRC http://irc.oftc.net/ doesn't work for me

**Comment by BillyDonahue** [comment]
Hi, I am actually doing exactly this change as a test balloon for the new git workflow. We'll be taking patches from this side soon, but not quite yet. We have to keep master in sync with a private snapshot for now. Let's wait on this PR until we've got the kinks worked out. Thx.

**Comment by KindDragon** [comment]
Please fix IRC link and Releases to https://github.com/google/googletest/releases

**Comment by BillyDonahue** [comment]
Resolve and reopen?

**Pull request closed without merging**
