### PR TITLE
Allow macros inside of parametrized test names.

### PR DESCRIPTION
**Pull request by sheepmaster**
This allows doing things like TEST_P(TestFixture, MAYBE(TestName)) for nicer conditional test disabling.

### CODE REVIEW

**Comment by sheepmaster** [comment]
@BillyDonahue, friendly ping? 😃

**Comment by BillyDonahue** [comment]
i'm not sure about this one.

the pre-stringified form might be desired.

**Comment by sheepmaster** [comment]
I don't think the unexpanded form would even be legal as a test name – after all, it would have to contain parentheses. I haven't seen any instances of test names that contain non-identifier characters.

Also, the current behavior is inconsistent with TEST_F, which does macro expansion in test names. (Another reason why I don't think anyone uses unexpanded macros in test names, as it would not work with TEST_F).

**Comment by BillyDonahue** [comment]
On Tue, Feb 9, 2016 at 4:34 PM, Bernhard Bauer <notifications@github.com>
wrote:

> I don't think the unexpanded form would even be legal as a test name –
> after all, it would have to contain parentheses.
>
Wouldn't a macro that isn't function-like also be expanded?
#define X abc123

TEST_F(Case, X)   <== Would this 'X' turn into abc123

**Comment by sheepmaster** [comment]
True, a non-function macro would also be expanded. In your specific example however, the "X" would already get expanded today, because TEST_F does that (and Chromium relies on this heavily to conditionally disable tests). It's just TEST_P that behaves differently for no apparent reason, and this has caused breakages in Chromium in the past.

**Comment by BillyDonahue** [comment]
ok. well can we have a test that does the TEST_F expansion near the test
for TEST_P expansion just to emphasize that they should behaviorally match?

**Comment by sheepmaster** [comment]
Sure! Done.

**Comment by gennadiycivil** [comment]
No CLA, closing

**Comment by sheepmaster** [comment]
Umm, where did you get that information? I'm a Chromium committer working for Google and created the commit from my Chromium account, so I should be covered under the Google / Chromium CLA. A search for my Github username on SignCLA also shows that I've signed the CLA on Dec 17, 2014 (https://goto.google.com/lsvwz).

Feel free to ping me directly (bauerb@) if you have any questions. Thanks!

**Comment by gennadiycivil** [comment]
The PR showed that CLA was still "pending" please feel free to re-open, (I have been cleaning up for some time now)

**Comment by gennadiycivil** [comment]
I just tried to re-open and it still shows
cla/google — Waiting for status to be reported. I am going to close again, please re-open and lets take a look

**Comment by sheepmaster** [comment]
I can't seem to reopen this request, but I created a new one, which also seems to pass the CLA check.

**Pull request closed without merging**
