### PR TITLE
gtest/gtest-printers.h : correct warning for msvc win32 (level /W3)

### PR DESCRIPTION
**Pull request by pthom**
Hi,

On 32 bits platforms, a prior casting to UInt32 before casting to UInt64 might be required to avoid some warnings (esp. for visual studio with elevated warning levels).

This problem occurs in some rare occasions :
- when using Visual Studio 2015 (other versions might be impacted)
- when compiling a 32 bits target on a 64 bits computer 
- when using elevated level warnings 
```cmake 
add_compile_options(/W3) 
add_compile_options(/we4826) 
```

In this setup, the following error is raised:
```
gtest/gtest-printers.h(437): error C4826: Conversion from 'const void *' to 'testing::internal::UInt64' is sign-extended. This may cause unexpected runtime behavior.
  gtest/gtest-printers.h(489): note: see reference to function template instantiation 'void testing::internal::DefaultPrintTo<const void>(testing::internal::IsNotContainer,testing::internal::true_type,T *,std::ostream *)' being compiled
          with
          [
              T=const void
          ]
  gtest/gtest-printers.h(529): note: see reference to function template instantiation 'void testing::internal::PrintTo<To>(const T &,std::ostream *)' being compiled
          with
          [
              To=const void *,
              T=const void *
          ]
```

This patch tries to detect the target environment under windows : this can be disabled by defining `GTEST_NO_PRINT_ENVIRONMENT_DETECTION`.
It might also be useful for other plaforms : in this case, one can define `GTEST_PRINT_ENVIRONMENT_32` before including `gtest.h` 

Hope this helps,

### CODE REVIEW

**Comment by pthom** [comment]
I signed the CLA

**Comment by gennadiycivil** [comment]
Aplogies for not getting to this sooner and thank you for your contribution. As part of release 1.8.x preparation I am closing all older PRs that have conflicts and/or failed CI. Please resolve conflicts.

**Comment by wkaluza** [comment]
I think this was fixed by #991.

**Comment by gennadiycivil** [comment]
Great, thank you

**Pull request closed without merging**
