### PR TITLE
Support for dynamic loading of shared test libraries

### PR DESCRIPTION
**Pull request by pimms**
The `testing::UnitTest::GetInstance()` method now returns a static
instance of type `testing::UnitTest*`. The instance is destroyable
through `testing::UnitTest::DeinitializeInstance()`, which is called
from `RUN_ALL_TESTS()`.

This PR allows dynamic loading of shared objects, DLLs and dylibs,
and running their aggregate set of tests as a single batch unit. This
is how we are doing testing at my company, but because of the
existing crashes, we have simply not unloaded our DLLs before
terminating the test-loading application.

Without these changes, if the test-containing DLLs are properly
unloaded, the test-case destructors cause segmentation faults, as
the test-cases has been unloaded.

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x1001782d8)
  * frame #0: 0x00000001000bff8d libgtest.dylib`testing::TestInfo::~TestInfo() + 45
    frame #1: 0x00000001000c0135 libgtest.dylib`testing::TestInfo::~TestInfo() + 21
    frame #2: 0x00000001000c22e7 libgtest.dylib`void testing::internal::Delete<testing::TestInfo>(testing::TestInfo*) + 39
    frame #3: 0x00000001000c2293 libgtest.dylib`void testing::internal::ForEach<std::__1::vector<testing::TestInfo*, std::__1::allocator<testing::TestInfo*> >, void (*)(testing::TestInfo*)>(std::__1::vector<testing::TestInfo*, std::__1::allocator<testing::TestInfo*> > const&, void (*)(testing::TestInfo*)) + 419
    frame #4: 0x00000001000c1fa4 libgtest.dylib`testing::TestCase::~TestCase() + 52
    frame #5: 0x00000001000c2335 libgtest.dylib`testing::TestCase::~TestCase() + 21
    frame #6: 0x00000001000c2359 libgtest.dylib`testing::TestCase::~TestCase() + 25
    frame #7: 0x00000001000d309b libgtest.dylib`void testing::internal::Delete<testing::TestCase>(testing::TestCase*) + 43
    frame #8: 0x00000001000d3043 libgtest.dylib`void testing::internal::ForEach<std::__1::vector<testing::TestCase*, std::__1::allocator<testing::TestCase*> >, void (*)(testing::TestCase*)>(std::__1::vector<testing::TestCase*, std::__1::allocator<testing::TestCase*> > const&, void (*)(testing::TestCase*)) + 419
    frame #9: 0x00000001000d2ab6 libgtest.dylib`testing::internal::UnitTestImpl::~UnitTestImpl() + 54
    frame #10: 0x00000001000d32d5 libgtest.dylib`testing::internal::UnitTestImpl::~UnitTestImpl() + 21
    frame #11: 0x00000001000d32f9 libgtest.dylib`testing::internal::UnitTestImpl::~UnitTestImpl() + 25
    frame #12: 0x00000001000d1d34 libgtest.dylib`testing::UnitTest::~UnitTest() + 68
    frame #13: 0x00000001000d02a5 libgtest.dylib`testing::UnitTest::~UnitTest() + 21
    frame #14: 0x00007fff6ade1069 libsystem_c.dylib`__cxa_finalize_ranges + 351
    frame #15: 0x00007fff6ade137a libsystem_c.dylib`exit + 55
    frame #16: 0x00007fff6ad3414c libdyld.dylib`start + 8
    frame #17: 0x00007fff6ad34145 libdyld.dylib`start + 1
```

### CODE REVIEW

**Comment by pimms** [comment]
I signed it!

**Comment by pimms** [comment]
This PR resolves #1283.

**Comment by pimms** [comment]
I realized I initially broke nearly **all** the test suites, so I've made some changes that should maintain all the existing functionality.

- Unloading the test cases is done explicitly through `testing::UnloadGoogleTest()`
- Implicit unloading behaves _nearly_ exactly as before
  _There might be some different semantics to when static members are destroyed
  compared to static function variables._

The static instance member is of type `std::shared_ptr<UnitTest>`, as `shared_ptr`s have the desired functionality _(explicitly resettable, implicitly destructed)_.

**Comment by pimms** [comment]
Using a custom class (`testing::UnitTest::Container`) instead of `std::shared_ptr`, as you're supporting pre-c++11 compilers.

**Comment by pimms** [comment]
I'm having serious issues getting the builds to pass through the CI systems.

I only have a MacBook available, but I've verified that the `travis.sh` script passes, with a reasonable subset of the variations Travis is running (`CXX_FLAGS=-std=c++11`, `CXX_FLAGS=`, `BUILD_TYPE=Debug`, `BUILD_TYPE=Release`) – they're all passing on my system, and I don't see how I'm breaking that many tests either.

Does anyone have some insight on this?

**Comment by gennadiycivil** [comment]
CI tests failed

**Comment by pimms** [comment]
I was thinking more in terms of whether or not I was missing something related to Windows or Travis, because I can't get it to fail on MacOS. I built it on Windows _(release, static library, x64, VS2015)_. Optionally, if I've missed something in the documentation.

On MacOS I've been running the Travis script by setting environment variables, and running the `travis.sh` script. Running on MacOS 10.13 64 bit.

```
$> set CXX_FLAGS=-std=c++11
$> set BUILD_TYPE=Release
$> ./travis.sh
~snip~
58/60 Test #58: gtest_uninitialized_test ................   Passed    0.16 sec
      Start 59: gtest_xml_outfiles_test
59/60 Test #59: gtest_xml_outfiles_test .................   Passed    0.19 sec
      Start 60: gtest_xml_output_unittest
60/60 Test #60: gtest_xml_output_unittest ...............   Passed    0.23 sec

100% tests passed, 0 tests failed out of 60

Total Test time (real) =  12.00 sec
```

**Comment by gennadiycivil** [comment]
I see both AppVeyor and Travis builds failed.

**Comment by gennadiycivil** [comment]
Closing, CI builds failing

**Comment by brandon-kohn** [comment]
Supporting this seems like a good idea which shouldn't require much of a change. What is the issue blocking this?

**Comment by pimms** [comment]
I never got around to fixing this back in October. Thanks for the reminder - although I've since changed jobs, this might be a useful feature for someone else. I've worked out the issues with Travis _(i think!)_, sending PR in a few.

**Pull request closed without merging**
