### PR TITLE
provide alternative for DebugBreak()

### PR DESCRIPTION
**Pull request by leissa**
This uses asm("int3") for clang/gcc on x86 as alternative for DebugBreak()

### CODE REVIEW

**Comment by gennadiycivil** [comment]
@leissa Thank you for this contribution. Could you please explain what problem is this solving and why this would be advantageous for the master branch?

**Comment by leissa** [comment]
This patch increases the user experience for platforms which don't support ```DebugBreak()```. ```asm("int3")``` does the same for x86-based systems. This means, on my linux system the following happens without the patch:
```
gdb ./my_unit_tests --gtest_break_on_failure
```
1. On the first failure I'll get a segmentation fault because of the ```*static_cast<volatile int*>(NULL) = 1;```
2. Then in the debugger I can look around, inspect values, and so forth but I cannot ```continue``` program execution.

With this patch, I can ```continue``` in ```gdb``` because ```int3``` is just a usual break point.

**Comment by gennadiycivil** [comment]
@leissa Could you please confirm consent of ALL commit author(s). For some reason the bot is having trouble . Did you write ALL code in this PR and if not could you confirm that all authors are OK wit this PR to be merged into googletest?
Thanks

**Comment by leissa** [comment]
@gennadiycivil I was puzzled by that, too. I'm the only author and this patch only takes 3 lines of code with two commits:
* 11855d8ef08567c7961fb3c6562fbe6f9b479092 is the original 3-line patch
* d04bf07fadd204881df4c7114906fa63b1b80c48 fixes a typo in a comment.
That's it.

**Pull request merged**
