### PR TITLE
Add x64 configuration

### PR DESCRIPTION
**Pull request by fojogit**

### CODE REVIEW

**Comment by KindDragon** [comment]
I have already this changes in PR #811

**Comment by fojogit** [comment]
@KindDragon Ok great! I see the x64 configs added in the msvc\2010 folder, is there another change that applies those to the msvc\2015 files?

**Comment by KindDragon** [comment]
@fojogit I think we should remove it because in general that project unsupported. Users should use CMake generated projects

**Comment by gennadiycivil** [comment]
AppVeyor build failed
Cleaning up PRs that
1) Don't have all checks OK
2) Have been around for a while with no activity

**Pull request closed without merging**
