### PR TITLE
Add docs in Korean

### PR DESCRIPTION
**Pull request by hyukmyeong**
This work has been started with https://github.com/google/googletest/issues/2337
It must be grateful to review whether this work is still necessary

※ I followed linux kernel doc dir structure
(https://github.com/torvalds/linux/tree/master/Documentation/translations/ko_KR)

### CODE REVIEW

**Comment by kuzkry** [comment]
Duuuude... 😲 But if I understand it right, would non-korean speakers still only bother English counterparts?

**Comment by hyukmyeong** [comment]
@googlebot

**Comment by hyukmyeong** [comment]
@googlebot I fixed it.

**Comment by hyukmyeong** [comment]
ㄴ

**Comment by hyukmyeong** [comment]
@kuzkry 

thank you for your comment!
I actullay change pull request cuz cla issue

Do you mean that it needs docs in other languages as well with below comment??
I'm sorry for my bad English

Duuuude... astonished But if I understand it right, would non-korean speakers still only bother English counterparts?

**Comment by kuzkry** [comment]
I wanted to know how we will keep it synchronised.
But I've already noticed this issue was already addressed in the attached issue by the maintainers.

**Comment by hyukmyeong** [comment]
@kuzkry

Thank you for the comment as always!
As I said in https://github.com/google/googletest/issues/2337 I and other Koreans will update docs^^

**Pull request closed without merging**
