### PR TITLE
Removing commas.

### PR DESCRIPTION
**Pull request by MR-A0101**
Readme Update!

### CODE REVIEW

**Comment by derekmauro** [comment]
Please sign the CLA.

**Comment by code-Vlack** [comment]
@MR-A0101 please assign this to me

**Comment by MR-A0101** [comment]
I have signed my CLA @derekmauro

**Review by Anucha7736zxc — CHANGES_REQUESTED** [review]
pli=1
idpid=C03llg7wc
SAMLRequest=nVJNj9owEP0rke8kIUuFahEqFrYqEmUjPvawN9cZwFpnJvVMoOyvr6EfqBcOPfjgp/fmvTf2CDnXk04OuILvHbAkPxqPrCNcqi6gJsMuXk0DrMXq9eTrQhdprttAQpa8+ivo3xcYZgjiCFUyn5XK1b2P0lYyfHNP2+UqNMeCVPICgSOlVFERecwdzJHFoEQoL4pePuj1h5v+QH8odDF4VcksZnZo5Ko6iLSss8xYSx0Kp3uivYfUUpNRxqbxRebq9lM8ri6n+YP3++HJqqT63ebRYe1wf7/Jt18k1l82m6pXPa83Kpn8aTcl5K6BsIZwdBa2q8UtliXc+Q7QQvpuvMGaUgS55oqRWY1HcYv62joknyk0Ru4nuSBxkbsrVQOKk7Ma32xG2W3gZXiul1Exn1XknT3/h0V7eR+W6BQre0+naQAjUKqd8QwqycYXy39/1Pgn
RelayState=/display/TG/OPEN+SOURCE?

**Comment by Anucha7736zxc** [comment]
Hi,

Congrats on creating your first Crowdin project!
My name is Maryna and as an onboarding manager at Crowdin, I’m here to make
getting started a little bit easier for you :)

Here’s what to do next:
- Upload your files
- Choose your translation strategy and invite translators

By the way, what do you want to accomplish with Crowdin?
Feel free to reply directly to this email. To discuss your localization
project book a quick call:
https://app.hubspot.com/meetings/crowdin-team/demo

Thanks for choosing Crowdin!

--
Sincerely,
Maryna
Customer Success Manager at Crowdin

Unsubscribe from emails like this.

ในวันที่ อ. 19 เม.ย. 2022 02:57 น. copybara-service[bot] <
***@***.***> เขียนว่า:

**Pull request merged**
