### PR TITLE
Make DoubleNearPredFormat fail on bad epsilons

### PR DESCRIPTION
**Pull request by randomascii**
DoubleNearPredFormat will happily accept epsilon values (abs_error) that
are so small that they are meaningless. This turns EXPECT_NEAR into a
complicated and non-obvious version of EXPECT_EQUAL.

This change modifies DoubleNearPredFormat) to calculate the smallest
meaningful epsilon value, given the input values, and then fail if
abs_error is smaller than that.

With this change the flaky test mentioned in crbug.com/786046 goes from
a flaky test to this 100% reliable failure:

../../base/time/time_win_unittest.cc(292): error: The epsilon used to
compare expected_microseconds_since_origin and
converted_microseconds_since_origin is less than the minimum epsilon in
this range, which is 512, where
expected_microseconds_since_origin evaluates to 3.640989196237484e+18,
converted_microseconds_since_origin evaluates to 3.640989196237484e+18, and
1.0 evaluates to 1.
ticks=9223372036854775807, to be converted via logic path: SAFE

This fixes issue #1350

### CODE REVIEW

**Comment by randomascii** [comment]
This pull request makes EXPECT_NEAR stricter on the values that it will accept. Therefore it may cause new failures in any software which uses googletest. That is both unfortunate (nobody likes causing downstream breaks) and the entire point of this change (bad tests *should* fail).

I have verified that this change detects the known bad test in Chromium's base_unittests and that no other failures in that test binary were found. Once this lands I will test all of Chromium's other tests and make any necessary fixes.

**Comment by randomascii** [comment]
How does this look? The change works now and should detect misuse of EXPECT_NEAR. Merge?

**Comment by gennadiycivil** [comment]
@randomascii 
Thank you for this contribution! In general for googlers the [guidelines](https://github.com/google/googletest/blob/7f8fefabedf2965980585be8c2bff97458f28e0b/googletest/docs/DevGuide.md#submitting-patches) suggest CL - first. 
 Waiting for the corresponding internal CL to land. Once it is submitted please make sure that the CL and this PR are in sync ( there might be changes in the CL in process ) and then we can merge it. 
Thank you!

**Comment by randomascii** [comment]
Acknowledged. I saw the guidance about creating internal CLs first only after I completed this one :-) but I will finish it and then copy it over to here.

**Comment by gennadiycivil** [comment]
Closing for now, just for cleanup. Please come back when CL is ready

**Pull request closed without merging**
