### PR TITLE
Add move semantics to mock objects.

### LINKED ISSUE #1155: Add move semantics to mock objects
Adding move semantics to mock objects makes it easier to mock using templates instead of interfaces. The following example does not work unless either 1) mock objects support move semantics, or 2) Foo stores a pointer to the implementation -- which might not be desirable.

```c++
template<typename Impl>
class Foo {
public:
  Foo(Impl impl = Impl{})
    : impl_{std::move(impl)}
  {}

  int bar() {
    return impl_.bar();
  }

private:
  Impl impl_;
};

class MockFooImpl {
public:
  MOCK_METHOD0(read, int());
};

TEST(EventTest, Example) {
  MockFooImpl mock;
  EXPECT_CALL(mock, read())
    .WillOnce(Return(1));

  Foo<MockFooImpl> foo{std::move(mock)};
  EXPECT_EQ(1, foo.bar());
}
```

### PR DESCRIPTION
**Pull request by betabandido**
Adding move semantics to mock objects makes it easier to mock using templates instead of interfaces. The following example does not work unless either 1) mock objects support move semantics, or 2) `Foo` stores a pointer to the implementation -- which might not be desirable.

```c++
template<typename Impl>
class Foo {
public:
  Foo(Impl impl = Impl{})
    : impl_{std::move(impl)}
  {}

  int bar() {
    return impl_.bar();
  }

private:
  Impl impl_;
};

class MockFooImpl {
public:
  MOCK_METHOD0(read, int());
};

TEST(EventTest, Example) {
  MockFooImpl mock;
  EXPECT_CALL(mock, read())
    .WillOnce(Return(1));

  Foo<MockFooImpl> foo{std::move(mock)};
  EXPECT_EQ(1, foo.bar());
}
```

This pull requests fixes #1155

### CODE REVIEW

**Comment by cjmay** [comment]
I think the appveyor failure was unrelated to this changeset---I rebased @betabandido's commits and all tests pass ([travis](https://travis-ci.org/cjmay/googletest/builds/256386691), [appveyor](https://ci.appveyor.com/project/cjmay/googletest)).  Any update on getting this merged?

**Comment by betabandido** [comment]
I have just synced my fork against the upstream repository, and as @cjmay well said all the tests are passing. I believe when I initially submitted this PR, tests on appveyor were failing for all other PRs too. It would be great if this PR got some traction and finally got merged.

**Comment by MakersF** [comment]
Is there any news for this?
Not being able to move mock objects is really challenging when testing templated libraries

**Comment by gennadiycivil** [comment]
Aplogies for not getting to this sooner and thank you for your contribution. As part of release 1.8.x preparation I am closing all older PRs that have conflicts and/or failed CI. Please resolve conflicts.

**Comment by gennadiycivil** [comment]
Please provide test results before / after that indicate that the change actually works and does what it is supposed to do. Unit test comes to mind 
Thanks

**Comment by cjmay** [comment]
@gennadiycivil @betabandido not sure what's being requested here, but just in case: in a separate branch I reorganized @betabandido's changes into two commits, (1) test and (2) implementation, and the tests fail on the first commit (but succeed on the second, when the implementation is added).  See the builds for [the bb branch](https://github.com/cjmay/googletest/commits/bb):

https://travis-ci.org/cjmay/googletest/builds

https://ci.appveyor.com/project/cjmay/googletest/history

**Comment by gennadiycivil** [comment]
@cjmay thank you, this is exactly what I was looking for, failed test first and successful test with the changes.

**Comment by gennadiycivil** [comment]
@betabandido Thank you for your contribution.

Internal review, results. 
Not sure if move can be implemented with the current design, closing for now. Please consider coming back to this after we release 1.8.x 

1) Take a look at the mock object. It contains a `void*` pointing back to the owner. This field will break with the =default move and contain garbage. 

2) Mock objects are registered by pointer. moving them changes their pointer identity

3) =default move constructors are rarely correct. Is the moved-from valid at all?

**Pull request closed without merging**
