### PR TITLE
use cmake build type defined in .travis.yml for travis builds

### LINKED ISSUE #1175: Some tests are failing when using the debug configuration (-DCMAKE_BUILD_TYPE=Debug) on Debian
I use the master branch:
>commit ca102b1f9d1f4c8a8c6f7a87b3e80d0af4b8789f
Merge: 50f3baf a2451c7
Author: Gennadiy Civil <gennadiycivil@users.noreply.github.com>
Date:   Thu Aug 3 16:49:13 2017 -0400

The following tests FAILED:
         29 - gtest_break_on_failure_unittest (Failed)
         30 - gtest_catch_exceptions_test (Failed)
         31 - gtest_color_test (Failed)
         32 - gtest_env_var_test (Failed)
         33 - gtest_filter_unittest (Failed)
         34 - gtest_help_test (Failed)
         35 - gtest_list_tests_unittest (Failed)
         36 - gtest_output_test (Failed)
         37 - gtest_shuffle_test (Failed)
         38 - gtest_throw_on_failure_test (Failed)
         39 - gtest_uninitialized_test (Failed)
         40 - gtest_xml_outfiles_test (Failed)
         41 - gtest_xml_output_unittest (Failed)

Note that if I use the **default** build configuration (without -DCMAKE_BUILD_TYPE=Debug) then everything is OK:
> cmake -Dgtest_build_tests=ON ..
all tests pass (100% tests passed, 0 tests failed out of 41).

System details:
> uname -a
Linux debian 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
> gcc --version
gcc (Debian 6.3.0-18) 6.3.0 20170516
> cmake --version
cmake version 3.7.2

I attached the output of 'cmake' and 'make test' commands.

[cmake-output.txt](https://github.com/google/googletest/files/1202234/cmake-output.txt)
[make-test-output.txt](https://github.com/google/googletest/files/1202235/make-test-output.txt)

### PR DESCRIPTION
**Pull request by hethi**
Currently, the `BUILD_TYPE` variable of `.travis.yml` was ignored up to now by `travis.sh` and the build process.

Also, while cmake does not complain on build type `debug` (as listed in .travis.yml currently), the cmake documentation always spells it `Debug`, so take this.

Using the variable in `travis.sh` to call `cmake -DCMAKE_BUILD_TYPE=Debug` leads to the problem reported in issue #1175, i.e. some Python driven tests won't find their test executable.

The travis build triggered by the first commits here will probably fail; then a fix can be tested and discussed.

This pull request fixes #1175 and #1070.

### CODE REVIEW

**Comment by hethi** [comment]
As expected, [Travis build 853](https://travis-ci.org/google/googletest/builds/269929046) is failing, i.e. CTest is failing with error messages as the following:
```
      Start 60: gtest_xml_output_unittest

60/60 Test #60: gtest_xml_output_unittest ...............***Failed    0.05 sec

Unable to find the test binary "/home/travis/build/google/googletest/build/googlemock/gtest/Debug/gtest_xml_output_unittest_". Please make sure to provide a path to the binary via the --build_dir flag or the BUILD_DIR environment variable.
```
The build type `Debug` was part of the path to the executable, which is wrong for this Cmake generator.
Trying to fix this now, though it might affect Windows which I'm unable to test currently - but AppVeyor will show it ...

**Comment by hethi** [comment]
Ok, unfortunately, `${CMAKE_CFG_INTDIR}` is set during **build** only, not during test, so AppVeyor is complaining now. Seems we need a small switch here.

**Comment by hethi** [comment]
@gennadiycivil As soon as AppVeyor has finished, this is ready for review :-)

**Comment by gennadiycivil** [comment]
Looks mostly good to me - but can we add tests for positive proof?
It would be helpful to show simple test case "before" that was failing and then show same test "After"
I think you mostly have this , but if you could make it easier to review I would really appreciate it

**Comment by hethi** [comment]
@gennadiycivil - I already tried to create comments here in sequence to show this, sorry that it wasn't obvious enough.

The failing build is mentioned in [this comment](https://github.com/google/googletest/pull/1235#issuecomment-325953906) with a link to the build logs, after turning on the build type in [travis.sh](https://github.com/google/googletest/pull/1235/files#diff-f9a62833538ab14fff849c2be16ab986) in commit [cc246](https://github.com/google/googletest/pull/1235/commits/cc246ecb5675983a879af97b0b466c6d7d64d308) - together with commit [dae04](https://github.com/google/googletest/pull/1235/commits/dae044d4b9869db985f32eeec78889440f646fb7) to use the CMake typical `Debug` instead of `debug` in [.travis.yml](https://github.com/google/googletest/pull/1235/files#diff-354f30a63fb0907d4ad57269548329e3). All Python based tests are failing, as the path given to Python is wrong.

The following commits, i.e. the changes in [googletest/cmake/internal_utils.cmake](https://github.com/google/googletest/pull/1235/files#diff-9d37b1fc33b12af84364910c74110b88), fix the build path given to Python. This path was o.k. for Windows, i.e. added e.g. `Debug` as postfix, but didn't work on UNIXoid systems which do not have split directories for multiple configurations in the build path.

**Comment by hethi** [comment]
Hmm, [Travis build 888.6](https://travis-ci.org/google/googletest/builds/270459938) timed out after a warning, probably not source code related? Will merge master into this branch to see the result of the next build.

**Pull request merged**
