### PR TITLE
Split gmock-matchers_test into 4 smaller test

### PR DESCRIPTION
**Pull request by ellert**
This is an updated version of #3199.
The reasons for proposing the split are still the same. In fact since the split was fisrt proposed the test has grown even more, and is causng even more problems.

### CODE REVIEW

**Comment by ellert** [comment]
Information to the reviewer: There is no new code here. One huge file (gmock-matchers_test.cc) is split into 5 smaller ones. The following list shows which lines of the file has been moved where:

🟥🟧🟨🟩🟦 1-34 (copyright)
🟧🟨🟩🟦 35-42 (start of pragmas)
🟥 43-72
🟥🟧🟨🟩🟦 73-76 (start of namespcae)
🟥 77-109
🟩 110-115
🟥 116-144
🟩 145-152
🟥 153-172
🟧 173-1792
🟩 1793-1798
🟧 1799-2166
🟨 2167-2829
🟩 2830-2856
⬜ 2857
🟨 2858-3096
🟧 3097-3169
🟨 3170-3241
🟩 3242-3306
🟨 3307-3744
🟩 3745-3885
🟧 3886-3983
🟩 3984-4817
🟧 4818-4886
🟦 4887-5001
🟩 5002-5074
🟦 5075-5275
🟩 5276-6201
🟦 6202-6456
🟧 6457-6473
🟦 6474-6500
🟩 6501-6858
🟦 6859-7037
🟩 7038-7043
🟨 7044-7049
🟦 7050-7187
🟩 7188-7688
🟦 7689-8076
🟩 8077-8208
🟦 8209-8421
🟨 8422-8483
🟦 8484-8684
🟥🟧🟨🟩🟦 8685-8688 (end of namespace)
🟧🟨🟩🟦 8689-8691 (end of pragmas)

Legend:
🟥 gmock-matchers_test.h
🟧 gmock-matchers1_test.cc
🟨 gmock-matchers2_test.cc
🟩 gmock-matchers3_test.cc
🟦 gmock-matchers4_test.cc
⬜ Removed empty line

**Comment by ellert** [comment]
@derekmauro It's been three weeks since you assigned this PR to yourself. If you need additional information about the proposed change, let me know.

**Review by derekmauro — CHANGES_REQUESTED** [review]
Two issues:
1) The Bazel build file needs to be updated as well.
2) Please don't just name the files 1-4. Please see if you can figure out a name for the files that better reflects their contents.

**Comment by ellert** [comment]
> 1. The Bazel build file needs to be updated as well.
I made a change here, and the CI tests for Linux and MacOS succeeded. The failure on Windows seems unrelated.

> 2. Please don't just name the files 1-4. Please see if you can figure out a name for the files that better reflects their contents.
I tried to come up with some names.

**Comment by ellert** [comment]
@derekmauro I have addressed your change requests. Let me know if it is satisfactory.

**Comment by ellert** [comment]
The PR was rebased to resolve conflicts.

**Comment by ellert** [comment]
@derekmauro This seems to have stalled...

**Comment by ellert** [comment]
This PR has now - for the third time - been rebased due to conflicts.
Let me know if there are still issues with the proposed changes that prevent the PR from being accepted.

**Comment by derekmauro** [comment]
Sorry for the delay. There is nothing wrong with this PR, but importing these things is harder than just pushing the Merge button. There is additional work involved (more than most PRs), I need to find time to do it, and this PR isn't really solving a practical problem for most users, so it isn't high on my priority list.

**Comment by ellert** [comment]
> ,,,, and this PR isn't really solving a practical problem for most users, so it isn't high on my priority list.

The googletest package build for Debian currently disables the build of the gmock-matchers_test on several architectures because the compilation of the test uses more memory than is available on the build servers:
* alpha
* armel
* hurd-i386
* mipsel
* sh4

**Comment by ellert** [comment]
Rebased again.
Can you please treat this seriously - I am not tryimg to fix a non-existing issue.

**Comment by ellert** [comment]
Thank you.

**Pull request closed without merging**
