### PR TITLE
Issue #1967: Add Mock::WaitForAndClearExpectations() for async effect testing.

### PR DESCRIPTION
**Pull request by calder**
See #1967 for background.

### CODE REVIEW

**Comment by gennadiycivil** [comment]
ping

**Comment by calder** [comment]
@gennadiycivil: I got some time to look at this. All builds are now passing.

**Comment by calder** [comment]
@gennadiycivil: Friendly ping.

**Comment by gennadiycivil** [comment]
@calder 

Looking at your example it does not appear that this should be part of the mocking framework.

>>>
Foo takes a Bar in its constructor.
Foo::DoSomething() calls Bar::DoSomethingElse() asynchronously (via std::async for example).
>>>

so, continuing here once you call Bar::DoSomethingElse() asynchronously via std::async, you get std::future back where you could call std::future::get to get the result https://en.cppreference.com/w/cpp/thread/future/get

This just does not appear to be withing mocking framework scope.

**Comment by calder** [comment]
@gennadiycivil: Yeah, that works great for functions that actually return a future. Some functions don't (and shouldn't) return a future or provide any way of determining when asynchronous side effects have completed.

As an example, this crops up a lot in eventually consistent open loop controllers like network programmers.

**Comment by sbenzaquen** [comment]
On Sun, Dec 30, 2018 at 2:53 AM Calder Coalson <notifications@github.com>
wrote:

> @gennadiycivil <https://github.com/gennadiycivil>: Yeah, that works great
> for functions that actually return a future. Some functions don't (and
> shouldn't) return a future or provide any way of determining when
> asynchronous side effects have completed.
>
If there is no way to know when the side effects have completed, then there
is no way to wait for them.
Waiting on some mock method to be called is not enough. The caller of that
method is still running and waiting for the result.

Even if you want to notify the test when the mock method is called, you can
easily do that from your end without extra support from the testing
framework.
Just specify the action on the mock method to signal some notification.

Eg, the example in
https://en.cppreference.com/w/cpp/thread/condition_variable is more or less
what you want, except that the notify_one happens in the action, like:

EXPECT_CALL(mock, Foo()).WillOnce([&] {
  std::unique_lock<std::mutex> lk(m);
  done = true;
  cv.notify_one();
});

This could be simpler if you have a higher level abstraction,
like absl::Notification, like:

absl::Notification notification;
EXPECT_CALL(mock, Foo()).WillOnce([&] { notification.notify(); });
notification.WaitForNotification();

> As an example, this crops up a lot in eventually consistent open loop
> controllers like network programmers.
>
Sometimes when the background system is really async you just have to
poll-and-sleep waiting for the results. This is a last ditch option, but
works.
Like:
while (!IsSideEffectDone()) absl::SleepFor(absl::Microseconds(10));

Obviously, whatever `IsSideEffectDone` is checking has to be properly
synchronized. You can't look at unsynchronized data that some other thread
might write because that has undefined behavior.

**Comment by calder** [comment]
@sbenzaquen: That works, but adds a lot of boilerplate to every async-satisfied expectation.

See https://github.com/google/googletest/issues/1967#issuecomment-441458616 for previous discussion of alternatives.

**Comment by calder** [comment]
@gennadiycivil: Friendly ping.

**Comment by gennadiycivil** [comment]
@calder Thank you again for this effort. As discussed, this extra support for the async execution is outside of what we deem reasonable for the testing/mocking framework.
Appreciate your effort and good design conversation but we can not accept it.

**Comment by calder** [comment]
@gennadiycivil: Sorry, I don't think I understand that reasoning.

It seems like 2 features are pretty fundamental to any mocking framework:
1. Simplify injection of behavior for testing how production code responds in certain scenarios.
2. Simplify assertions about the behavior of production code under these scenarios.

Both of these are *possible* without a mocking framework; mocking frameworks just make expressing them *simpler and more readable*.

@leunMar and I are saying that as users of GMock, a `WaitForAndClearExpectations()` helper would make assertions about a specific class of behavior (asynchronous side effects) *simpler and more readable*. If (2) is indeed a goal of any mocking framework, then this change falls squarely within that goal.

So while it's fair to reject this feature as too niche to be worth the burden of the increased API surface area, I don't think it's fair to say it's out of scope for a mocking framework.

# Alternative

If the GMock team decides this feature is indeed too niche to support, we could ideally still implement it in our own code bases. This is currently impossible because there's no public interface for testing if a Mock's expectations have been met. Exposing a `Mock::AreExpectationsMet()` function would enable this.

**Comment by calder** [comment]
Thanks for the resonse @sbenzaquen. I can definitely see the potential for misuse, I just also see a decent potential for valid (non-racy) use.

A simple example is a class whose destructor drains all outstanding asynchronous operations, but whose individual methods do not provide an API for determining when their asynchronous side effects have completed.

If you all think the cost of potential misuse exceeds the benefit to valid users, I'll suck it up and continue to maintain a private fork.

**Pull request closed without merging**
