### PR TITLE
Fixed warnings

### PR DESCRIPTION
**Pull request by JohanMabille**
Backport of #2722

### CODE REVIEW

**Comment by kuzkry** [comment]
Hi! On [releases](https://github.com/google/googletest/releases) webpage you will find release 1.10.0 and a note:
> The 1.10.x will not consider any requests for any new features, The bug fix requests will only be considered if proven "critical"

Warning isn't critical, so this pull request targeting [v.1.10.x](https://github.com/google/googletest/tree/v1.10.x) branch should be abandoned.

**Comment by JohanMabille** [comment]
This warning prevents to build gtest 1.10 with recent versions of gcc and you consider it as non critical?

**Comment by kuzkry** [comment]
It's only a warning after all. What prevents build is `-Werror` applied onto `-Wsign-conversion`.
Who knows, maybe GTest maintainers will accept it.

**Comment by JohanMabille** [comment]
> What prevents build is `-Werror` applied onto `-Wsign-conversion`.

Indeed, but I guess they set `-Werror`  on purpose, so fixing the warning seems to be the thing to do rather than unsetting `-Werror` (or unsetting it for particular warnings).

**Pull request merged**
