### PR TITLE
Fix `-Wsign-conversion` issues

### PR DESCRIPTION
**Pull request by ngie-eign**
This PR takes a different approach by tackling individuals issues without changing internal API construction, as I tried in #2165.

This makes googletest compile cleanly with `clang++ -Wconversion`, fixing #2146.

### CODE REVIEW

**Comment by EricWF** [comment]
This patch looks a lot better. Thank you.

**Comment by ngie-eign** [comment]
Thanks for the feedback @EricWF! I’ll force-push my newer revision soon which touches more areas affected by this warning.

**Comment by ngie-eign** [comment]
I've addressed the remaining issues via casting, etc. Please feel free to review!

**Comment by ngie-eign** [comment]
@gennadiycivil: ping?

**Comment by ngie-eign** [comment]
I see there are issues I need to resolve before this can be merged.

**Comment by ngie-eign** [comment]
@EricWF, @gennadiycivil: I fixed the issues, so CI once again passes on this branch (and I fixed some issues with incoming code as well in the past few days). Please re-review this PR. Thank you!

**Comment by ngie-eign** [comment]
And I broke it by accident with a force push.. I will unbreak it again soon.

**Comment by ngie-eign** [comment]
> And I broke it by accident with a force push.. I will unbreak it again soon.

Ok. Force pushed the right set of changes.

**Comment by ngie-eign** [comment]
@EricWF, @gennadiycivil: ready for review!

**Comment by ngie-eign** [comment]
Ping?

**Comment by ngie-eign** [comment]
@EricWF, @gennadiycivil: ping?

**Comment by ngie-eign** [comment]
@gennadiycivil: ping?

**Comment by gennadiycivil** [comment]
Looking, sorry for the delay

**Comment by ngie-eign** [comment]
> Looking, sorry for the delay

I'm trying again after rebasing. It seems that other changes have snuck in, in the past week, which are triggering failures on Linux >_>.

**Comment by ngie-eign** [comment]
@gennadiycivil: ok. CI is green again with the latest set of pushed changes.

**Comment by gennadiycivil** [comment]
We had an internal review and made small-ish changes, mostly formatting and trivial. I imported this PR before your latest commit so your latest changes are not here. The most expedient would be to make another PR to pick up the changes that could have been missed. 
Also please review the formatting changes we made.

Thank you

**Comment by elcabesa** [comment]
just try to compile google test a0d60bed4d0ea17c7130cda16776b9bc8a929d7b with clang 7.0.1 
this is the error coming out from cmake:

[  1%] Building CXX object googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.obj
In file included from C:\Users\elcab\Downloads\workspace\vajolet22\build\googletest-src\googletest\src\gtest-all.cc:41:
C:/Users/elcab/Downloads/workspace/vajolet22/build/googletest-src/googletest\src/gtest.cc:1694:43: error: implicit
      conversion changes signedness: 'long' to 'DWORD' (aka 'unsigned long') [-Werror,-Wsign-conversion]
                                          hr,  // the error
                                          ^~
In file included from C:\Users\elcab\Downloads\workspace\vajolet22\build\googletest-src\googletest\src\gtest-all.cc:45:
C:/Users/elcab/Downloads/workspace/vajolet22/build/googletest-src/googletest\src/gtest-port.cc:282:11: error: implicit
      conversion changes signedness: 'int' to 'DWORD' (aka 'unsigned long') [-Werror,-Wsign-conversion]
  ::Sleep(n);
  ~~      ^
In file included from C:\Users\elcab\Downloads\workspace\vajolet22\build\googletest-src\googletest\src\gtest-all.cc:46:
C:/Users/elcab/Downloads/workspace/vajolet22/build/googletest-src/googletest\src/gtest-printers.cc:179:28: error:
      implicit conversion changes signedness: 'signed char' to 'wchar_t' [-Werror,-Wsign-conversion]
      if (IsPrintableAscii(c)) {
          ~~~~~~~~~~~~~~~~ ^
C:/Users/elcab/Downloads/workspace/vajolet22/build/googletest-src/googletest\src/gtest-printers.cc:223:29: note: in
      instantiation of function template specialization 'testing::internal::PrintAsCharLiteralTo<unsigned char, signed
      char>' requested here
  const CharFormat format = PrintAsCharLiteralTo<UnsignedChar>(c, os);
                            ^
C:/Users/elcab/Downloads/workspace/vajolet22/build/googletest-src/googletest\src/gtest-printers.cc:248:3: note: in
      instantiation of function template specialization 'testing::internal::PrintCharAndCodeTo<unsigned char, signed
      char>' requested here
  PrintCharAndCodeTo<unsigned char>(c, os);
  ^
3 errors generated.
mingw32-make[2]: *** [googletest-build\googletest\CMakeFiles\gtest.dir\build.make:63: googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:110: googletest-build/googletest/CMakeFiles/gtest.dir/all] Error 2
mingw32-make: *** [Makefile:129: all] Error 2

**Comment by ngie-eign** [comment]
> On Apr 18, 2019, at 11:20, elcabesa <notifications@github.com> wrote:
> 
> just try to compile google test a0d60be with clang 7.0.1
> this is the error coming out from cmake:
> 
> [ 1%] Building CXX object googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.obj
> In file included from C:\Users\elcab\Downloads\workspace\vajolet22\build\googletest-src\googletest\src\gtest-all.cc:41:
> C:/Users/elcab/Downloads/workspace/vajolet22/build/googletest-src/googletest\src/gtest.cc:1694:43: error: implicit
> conversion changes signedness: 'long' to 'DWORD' (aka 'unsigned long') [-Werror,-Wsign-conversion]
> hr, // the error
> ^~
> In file included from C:\Users\elcab\Downloads\workspace\vajolet22\build\googletest-src\googletest\src\gtest-all.cc:45:
> C:/Users/elcab/Downloads/workspace/vajolet22/build/googletest-src/googletest\src/gtest-port.cc:282:11: error: implicit
> conversion changes signedness: 'int' to 'DWORD' (aka 'unsigned long') [-Werror,-Wsign-conversion]
> ::Sleep(n);
> ~~ ^
> In file included from C:\Users\elcab\Downloads\workspace\vajolet22\build\googletest-src\googletest\src\gtest-all.cc:46:
> C:/Users/elcab/Downloads/workspace/vajolet22/build/googletest-src/googletest\src/gtest-printers.cc:179:28: error:
> implicit conversion changes signedness: 'signed char' to 'wchar_t' [-Werror,-Wsign-conversion]
> if (IsPrintableAscii(c)) {
> ~~~~~~~~~~~~~~~~ ^
> C:/Users/elcab/Downloads/workspace/vajolet22/build/googletest-src/googletest\src/gtest-printers.cc:223:29: note: in
> instantiation of function template specialization 'testing::internal::PrintAsCharLiteralTo<unsigned char, signed
> char>' requested here
> const CharFormat format = PrintAsCharLiteralTo(c, os);
> ^
> C:/Users/elcab/Downloads/workspace/vajolet22/build/googletest-src/googletest\src/gtest-printers.cc:248:3: note: in
> instantiation of function template specialization 'testing::internal::PrintCharAndCodeTo<unsigned char, signed
> char>' requested here
> PrintCharAndCodeTo(c, os);
> ^
> 3 errors generated.
> mingw32-make[2]: *** [googletest-build\googletest\CMakeFiles\gtest.dir\build.make:63: googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.obj] Error 1
> mingw32-make[1]: *** [CMakeFiles\Makefile2:110: googletest-build/googletest/CMakeFiles/gtest.dir/all] Error 2
> mingw32-make: *** [Makefile:129: all] Error 2
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

I’ll send you a patch later on today/tomorrow to fix this (I will need to fire up my windows 10 machine, install the necessary tools, etc). I’m a bit (but not completely) surprised someone is compiling googletest in Cygwin with clang :)..

Thanks for the report!
-Enji

**Comment by elv-peter** [comment]
Broke my Emscripten build I think:
```
In file included from .../googletest-src/googletest/src/gtest-all.cc:41:
.../googletest-src/googletest/src/gtest.cc:1952:21: error: implicit conversion
      changes signedness: 'const wchar_t' to 'wint_t' (aka 'unsigned int') [-Werror,-Wsign-conversion]
    left = towlower(*lhs++);
           ~~~~~~~~ ^~~~~~
.../googletest-src/googletest/src/gtest.cc:1953:22: error: implicit conversion
      changes signedness: 'const wchar_t' to 'wint_t' (aka 'unsigned int') [-Werror,-Wsign-conversion]
    right = towlower(*rhs++);
            ~~~~~~~~ ^~~~~~
```

**Pull request closed without merging**
