### PR TITLE
default to enable threading on Solaris, AIX and z/OS

### LINKED ISSUE #3990: Default to GTEST_HAS_PTHREAD=1 for AIX, Solaris and z/OS
**Does the feature exist in the most recent commit?**

No, see https://github.com/google/googletest/blob/main/googletest/include/gtest/internal/gtest-port.h#L534

**Why do we need this feature?**

It's possible to patch/replace `gtest/internal/custom/gtest-port.h` or build everything with `-DGTEST_HAS_PTHREAD=1` to enable thread-support for additional platforms. But it would be easier & safer if threading was enabled by default on platforms that support it. We currently maintain a local patch to enable threading for AIX, Solaris and z/OS because we use GTest on those platforms with threaded code. We'd like to upstream this change if possible.

**Describe the proposal**

Change the default definition of `GTEST_HAS_PTHREAD` to include `GTEST_OS_SOLARIS || GTEST_OS_AIX || GTEST_OS_ZOS`.

**Is the feature specific to an operating system, compiler, or build system version?**

No.
I suspect it's possible that ancient AIX, Solaris or z/OS versions didn't support POSIX threads, but I wouldn't know what the minimum version is. I propose to just extend the definition of `GTEST_HAS_PTHREAD` by `GTEST_OS_SOLARIS || GTEST_OS_AIX || GTEST_OS_ZOS` without any version checks - just like for the platforms that already default to "thread support on".

### PR DESCRIPTION
**Pull request by pgroke-dt**
fix #3990

### CODE REVIEW

**Review by derekmauro — COMMENTED** [review]
I know it is annoying, but we need the CLA.

**Comment by pgroke-dt** [comment]
@derekmauro 
Yes, sorry, I know. I asked the team that handles CLAs to sign it and enter my email address, and they told me they did. Then I created 2 PRs and the check failed. I talked to them again and they said there was some issue with Google's CLA manager and they already opened an issue for it. I don't have details but I'll ping them again tomorrow.

**Comment by pgroke-dt** [comment]
For reference, the CLA issue is being discussed here: https://github.com/google/closure-compiler/pull/3988

**Comment by pgroke-dt** [comment]
@derekmauro Took some time, but we finally figured the CLA stuff out.

**Comment by pgroke-dt** [comment]
Hi. The CLA check is green now. There were failing tests, but I don't think they have anything to do with the changes in this PR - and I don't think I have permissions to (re-)run actions.

**Comment by pgroke-dt** [comment]
@derekmauro I'd really like to proceed with this. Please let me know if there's something I need to do before this can be merged.

**Review by Hellothuy1 — APPROVED** [review]

**Comment by pgroke-dt** [comment]
@Hellothuy1 thanks for approving. I have resolved the conflicts.

**Pull request merged**
