### PR TITLE
MSVC project work

### PR DESCRIPTION
**Pull request by tplunket**
This PR started just as an addition of VS2015 project files for gtest. The old project files were for VS2003 so they were moved to a subdirectory and the new project files were added to another subdirectory, mirroring what had been done in gmock. 64 bit targets were also added. This required output directories to be modified a little bit; x86/Win32 and x64 directories get all build outputs for their respective targets. I also tweaked the way that debug outputs get the 'd' suffixed on their name to allow more property sharing between projects and to not stomp things like the debug database when building multiple targets at once.

A bunch of common properties were pulled out of both projects' project files, into their respective projects' props files. Finally, scripts were added to automate building all targets and running all test executables.

### CODE REVIEW

**Comment by tplunket** [comment]
I signed it!

**Comment by tplunket** [comment]
The appveyor failed tests appear to be addressed by PR #1034.

**Comment by KindDragon** [comment]
PR #811 should fix this too, but no one merges them for more than 8 months 😞

**Comment by gennadiycivil** [comment]
Not sure why AppVeyor build failed, please take a look, and resubmit with working build for this to be considered
https://ci.appveyor.com/project/BillyDonahue/googletest/build/209

**Pull request closed without merging**
