### PR TITLE
Fix warnings with nvc++ as the compiler

### LINKED ISSUE #3849: Warnings with nvc++ as the compiler
**Describe the bug**

    The following warnings were observed when building googletest:
    
```
[ 12%] Building CXX object googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
"/ascldap/users/crtrott/Software/googletest/googletest/src/gtest-internal-inl.h", line 636: warning: unknown attribute "optimize"
        GTEST_NO_INLINE_ GTEST_NO_TAIL_CALL_;
                         ^

"/ascldap/users/crtrott/Software/googletest/googletest/src/gtest.cc", line 6252: warning: unknown attribute "optimize"
  GTEST_NO_INLINE_ GTEST_NO_TAIL_CALL_ std::string
                   ^

[ 25%] Linking CXX static library ../lib/libgtest.a
[ 25%] Built target gtest
Scanning dependencies of target gmock
Scanning dependencies of target gtest_main
[ 37%] Building CXX object googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 50%] Building CXX object googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
"/ascldap/users/crtrott/Software/googletest/googlemock/src/gmock-spec-builders.cc", line 674: warning: variable "l" was declared but never referenced
    internal::MutexLock l(&internal::g_gmock_mutex);
```

**Steps to reproduce the bug**

```
cmake -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_COMPILER=nvc++ ../
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is NVHPC 22.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /ascldap/users/projects/x86-64/nvidia/hpc_sdk/Linux_x86_64/22.3/compilers/bin/nvc++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python: /usr/bin/python3.6 (found version "3.6.8") found components: Interpreter 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /ascldap/users/crtrott/Software/googletest/build
```

**Does the bug persist in the most recent commit?**

This was tested with the latest commit 8d51dc50eb7e76

**What operating system and version are you using?**

RedHat 7.x
```
Linux kokkos-dev-2 3.10.0-1160.36.2.el7.x86_64 #1 SMP Thu Jul 8 02:53:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**What compiler and version are you using?**

```
nvc++ --version

nvc++ 22.3-0 64-bit target on x86-64 Linux -tp skylake-avx512 
NVIDIA Compilers and Tools
Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
```

**What build system are you using?**

cmake version 3.21.1

**Additional context**

The first issue can be resolved by checking for __NVCOMPILER in 
https://github.com/google/googletest/blob/8d51dc50eb7e7698427fed81b85edad0e032112e/googletest/include/gtest/internal/gtest-port.h#L772-L779

I.e. the rootcause seems to be that __NVCOMPILER does define _GNUC_, but its not really GCC. So just making sure that the GCC variant is only used when __NVCOMPILER is not defined fixes that warning. 

I would issue a PR, but not sure its worth the effort to get the corporate contributor agreement signed ..

The second warning, is likely on nvc++ itself (i mean the lock is clearly used and serves a function), however one could fix it with adding a `(void) l` in the code.

### PR DESCRIPTION
**Pull request by gonzalobg**
Closes #3849.

I've submitted a CLA.

### CODE REVIEW

**Review by ProKashif — APPROVED** [review]

**Comment by gonzalobg** [comment]
@ProKashif could you approve the workflow so that tests can pass and we can merge this? Thanks!

**Comment by gonzalobg** [comment]
@ProKashif @derekmauro the CI error looks unrelated to this PR. Do you know what caused this? (and if its unrelated, could we run CI again?). Thanks!

**Comment by gonzalobg** [comment]
@thughes maybe?

**Comment by thughes** [comment]
You could try rebasing on the latest `main`, which has fixes for the Windows CI that have landed since you opened the PR; pushing that may re-trigger the CI checks.

**Comment by gonzalobg** [comment]
@derekmauro ping

**Comment by gonzalobg** [comment]
Made a small change to trigger CI again, hopefully it won't spuriously fail again.
Due to the change, @ProKashif  this needs to be approved, again.

**Comment by gonzalobg** [comment]
@thughes ping

**Pull request merged**
