### PR TITLE
Added new macros to specify override or noexcept specifiers #533 #1821

### PR DESCRIPTION
**Pull request by Julien-Blanc-tgcm**
* following the model of MOCK_CONST_METHOD, added MOCK_NOEXCEPT_METHOD
* also added the MOCK_VIRTUAL_METHOD, which adds the override keyword
* added all combination of CONST / NOEXCEPT / VIRTUAL where it made
sense.

### CODE REVIEW

**Comment by AriehSchneier** [comment]
https://github.com/google/googletest/pull/704

**Comment by AriehSchneier** [comment]
Note I already created a pull request for this a while back, which included heavily cleaning up the pump file to remove a lot of the duplication that shouldn't have been in there.
https://github.com/google/googletest/pull/704

**Comment by Julien-Blanc-tgcm** [comment]
Didn't see your PR, apparently it was closed.

You did not handle noexcept, though, and i think MOCK_VIRTUAL is a better alternative than MOCK_NOOVERRIDE: it does not change the default behaviour, so it doesn't break any existing tests.

However, i could use something inspired by your logic to generate the combinatory.

**Comment by gennadiycivil** [comment]
No CLA. 
In addition we are actively discouraging new macros.

**Comment by AriehSchneier** [comment]
The difference is, I made it so by default every mock adds the override keyword, unless you specifically remove it (but added a flag to enable it for backwards compatibility).
Generally mocks are virtual, with only a few cases not being virtual.

**Comment by Julien-Blanc-tgcm** [comment]
> Generally mocks are virtual, with only a few cases not being virtual.

While that is true, the side-effect of the change must be taken into account. Adding the override keyword by default breaks every test that is not virtual. This can means, breaking a lot of tests. Adding a new macro does not change anything for existing code, does not break anything.

> In addition we are actively discouraging new macros.

While i understand that, i doubt there can be a solution for noexcept that does not incurs the usage of new macros. IIRC exceptions are not in use at google, so this may not be an issue, but is for any user that want to mock noexcept functions. Override can be handled with pragmas, noexcept can't.

**Comment by gennadiycivil** [comment]
No CLA means that we can not continue working on this, sorry.

**Comment by AriehSchneier** [comment]
> Adding the override keyword by default breaks every test that is not virtual.

That is why I added a flag that you need to turn on to enable the change.

**Pull request closed without merging**
