### PR TITLE
Fix warning C4819 in Visual Studio

### PR DESCRIPTION
**Pull request by duxiuxing**
When I include the gmock-all.cc to my visual studio project and compile, I got a few of warnings like these:

```
1>  gmock-all.cc
1>..\googlemock\include\gmock\internal\gmock-internal-utils.h : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>..\googlemock\include\gmock\gmock-generated-function-mockers.h : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>..\googlemock\include\gmock\gmock-spec-builders.h(1497): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
```

and then I found all these warnings are caused by the character "…", you can use Find in Files and get the results like these:

```
Find all "…", Subfolders, Keep modified files open, Find Results 1, "All Open Documents", ""
  ..\googlemock\include\gmock\gmock-generated-function-mockers.h(355)://     MockSpec<string&()> gmock_GetName() { … }
  ..\googlemock\include\gmock\gmock-generated-function-mockers.h(366)://     const string& gmock_GetName() const { … }
  ..\googlemock\include\gmock\gmock-spec-builders.h(1857)://   ON_CALL(mock, NoArgsMethod()).WillByDefault(…);
  ..\googlemock\include\gmock\gmock-spec-builders.h(1858)://   ON_CALL(mock, NoArgsMethod).WillByDefault(…);
  ..\googlemock\include\gmock\gmock-spec-builders.h(1861)://   ON_CALL(mock, TwoArgsMethod(_, _)).WillByDefault(…);
  ..\googlemock\include\gmock\gmock-spec-builders.h(1862)://   ON_CALL(mock, TwoArgsMethod).WillByDefault(…);
  ..\googlemock\include\gmock\gmock-spec-builders.h(1865)://   ON_CALL(mock, TwoArgsMethod(_, 45)).WillByDefault(…);
  ..\googlemock\include\gmock\gmock-spec-builders.h(1868)://   ON_CALL(mock, OverloadedMethod(_)).WillByDefault(…);
  ..\googlemock\include\gmock\gmock-spec-builders.h(1869)://   ON_CALL(mock, OverloadedMethod(_, _)).WillByDefault(…);
  ..\googlemock\include\gmock\gmock-spec-builders.h(1872)://   ON_CALL(mock, OverloadedMethod).WillByDefault(…);
  ..\googlemock\include\gmock\gmock-spec-builders.h(1880)://   ON_CALL(mock, TwoArgsMethod(_, 45))…
  ..\googlemock\include\gmock\gmock-spec-builders.h(1882)://   // …expands to:
  ..\googlemock\include\gmock\gmock-spec-builders.h(1883)://   mock.gmock_TwoArgsMethod(_, 45)(WithoutMatchers(), nullptr)…
  ..\googlemock\include\gmock\gmock-spec-builders.h(1887)://   // …which is essentially:
  ..\googlemock\include\gmock\gmock-spec-builders.h(1888)://   mock.gmock_TwoArgsMethod(_, 45)…
  ..\googlemock\include\gmock\gmock-spec-builders.h(1893)://   ON_CALL(mock, TwoArgsMethod)…
  ..\googlemock\include\gmock\gmock-spec-builders.h(1895)://   // …expands to:
  ..\googlemock\include\gmock\gmock-spec-builders.h(1896)://   mock.gmock_TwoArgsMethod(WithoutMatchers(), nullptr)…
  ..\googlemock\include\gmock\gmock-spec-builders.h(1900)://   // …which is essentially:
  ..\googlemock\include\gmock\gmock-spec-builders.h(1901)://   mock.gmock_TwoArgsMethod(_, _)…
  ..\googlemock\include\gmock\internal\gmock-internal-utils.h(351)://    ON_CALL(mock, Method({}, nullptr))…
  Matching lines: 21    Matching files: 3    Total files searched: 3
```

Replace "…" with "..."(three dots) could fix the warnings.

### CODE REVIEW

**Comment by duxiuxing** [comment]
What should I do for the errored check?

**Comment by duxiuxing** [comment]
Close pull request and reopen it would fire all checks.

**Comment by gennadiycivil** [comment]
Thank you for your contribution.
Could you please also change the gmock-generated-function-mockers.h.pump

**Comment by duxiuxing** [comment]
Find "…" replace with "..."(three dots) look in the whole directory, Done!

**Pull request merged**
