### PR TITLE
Fix for #1587

### PR DESCRIPTION
**Pull request by LukeCz**

### CODE REVIEW

**Comment by LukeCz** [comment]
I signed it!

**Comment by gennadiycivil** [comment]
No CLA. Please make sure you use the same github username / email when signing the CLA
Also CI failed, make sure to use the latest master as a base

**Comment by LukeCz** [comment]
I signed it!

**Comment by LukeCz** [comment]
The build failed with

ERROR: Analysis of target '//:gtest' failed; build aborted: no such package '@com_google_absl//absl/strings': The native http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.

It does not seem to be related to my change in any way...

**Pull request closed without merging**
