### PR TITLE
Remove gcc 6 misleading indentations warnings

### PR DESCRIPTION
**Pull request by Romain-Geissler**
This removes some simple warnings that I hit when using Gmock with gcc6 and -Wall -Wextra -Werror.

### CODE REVIEW

**Comment by Romain-Geissler** [comment]
I signed it!

**Comment by Romain-Geissler-1A** [comment]
Ping

**Comment by gennadiycivil** [comment]
Thank you very much for this contribution. Please provide testing output that clearly demonstrates before/after.

**Comment by Romain-Geissler-1A** [comment]
Huh I am not sure to understand. Gcc emits indentation warnings, this is a stylish fix for something that gcc considers is error prone. The patch itself can be debated if you want, but I doubt any unittest will change anything in that matter, since this is a pure stylish fix.

**Comment by gennadiycivil** [comment]
Hello. Just show the run before / after that's all, the warnings before and no warnings after, very simple

**Comment by Romain-Geissler-1A** [comment]
I could find an old unpatched gtest library where we had the issue. When I build with gcc 6 -Wall -Werror -Wextra, I get:

> /data3/mwrep/res/osp/Gmock/16-0-0-3/include/gmock/gmock-more-matchers.h: In member function ‘testing::internal::string testing::IsEmptyMatcher::gmock_Impl<arg_type>::FormatDescription(bool) const’:
> /data3/mwrep/res/osp/Gmock/16-0-0-3/include/gmock/gmock-more-matchers.h:48:1: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
>  MATCHER(IsEmpty, negation ? "isn't empty" : "is empty") {
>  ^~~~~~~
> /data3/mwrep/res/osp/Gmock/16-0-0-3/include/gmock/gmock-more-matchers.h:48:1: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’

with the patch, this warning disappears.

**Comment by gennadiycivil** [comment]
Thank you and sorry for the delay. 
Could you please take a look at the [style guide](https://google.github.io/styleguide/cppguide.html#Conditionals) for conditionals.

**Comment by gennadiycivil** [comment]
Ping

**Comment by Romain-Geissler** [comment]
Yep sorry for the delay.

I fixed the coding style, and regenerated the generated file with pump.py + rebased on top of current master.

**Pull request merged**
