### PR TITLE
Fixed a race condition between the Watcher thread and the main thread during program exit.

### PR DESCRIPTION
**Pull request by cgyrling**
A race condition exist between the Watcher thread and main(). A case was found where the Watcher thread does not get execution time before the main function returns and calls atexit(). At that point the Watcher thread started runing tls_init() code while the main thread was shutting down. This resulted in rare crashes and deadlocks.

This fixes the following issue: (https://github.com/google/googletest/issues/4493)

### CODE REVIEW

**Comment by derekmauro** [comment]
We can't get started on this without the CLA. Please sign the CLA and report back.

**Comment by cgyrling** [comment]
It shows me as part of this Corporate Contract 
Google Corporate CLA | Facebook, Inc. | Apr 29, 2016 12:42 PDT.

I double-checked all the emails used and I believe I should be good to go. No individual CLA needed to be signed

**Comment by derekmauro** [comment]
The CLA check is still failing. There is nothing I can do about that. Please figure out why.

If you would like to close this pull request I am happy to fix this myself (I would do it in a slightly different way anyway).

**Comment by cgyrling** [comment]
Hi Derek. I'm fine with you fixing the issue. I'm having CLA issues on my end that is holding me up.

**Pull request closed without merging**
