### PR TITLE
Port to borland

### PR DESCRIPTION
**Pull request by nevot**

### CODE REVIEW

**Comment by gennadiycivil** [comment]
@nevot please sign the CLA

**Comment by tanzislam** [comment]
Already tried this with #1217. 😄

**Comment by tanzislam** [comment]
One thing to note: Under the latest C++Builder (10.2 update 3; haven't checked earlier versions) a unit test is failing:

```
[----------] 1 test from IsHashTable
[ RUN      ] IsHashTable.Basic
..\test\gtest_unittest.cc:7588: Failure
Value of: testing::internal::IsHashTable<std::unordered_set<int>>::value
  Actual: false
Expected: true
[  FAILED  ] IsHashTable.Basic (3 ms)
[----------] 1 test from IsHashTable (5 ms total)
```

The implementation of `testing::internal::IsHashTable<T>::value` is based on the heuristic of `T` not having a `reverse_iterator` member type, but C++Builder's `std::unordered_set<T>` (from Dinkumware v6.50) unfortunately exposes the `reverse_iterator` member type from an implementation detail (`<xhash>`) and thus fails the test. (This member type is not documented in the accompanying `.chm` help file.) I'm not sure how to fix this situation.

**Comment by tanzislam** [comment]
Hi @gennadiycivil, would you be willing to accept this patch if I re-raise it myself again? (My original attempt was #1217.) Seems like @nevot has disappeared here. :confused:

**Comment by gennadiycivil** [comment]
NO CLA. In addition, please note that it is not feasible to support generated project information for all possible compilers.

**Pull request closed without merging**
