### PR TITLE
Issue #1735 It seems like CMAKE_CXX_FLAGS is getting double appended when buildin…

### PR DESCRIPTION
**Pull request by jschloss-swift**
Related to Issue #1735 

It seems like CMAKE_CXX_FLAGS is getting double appended when building as a nested cmake project,
which breaks my build as gcc does not allow -specs=nosys.specs to be called multiple times.
Removing this fixes it and seems to keep the same compile options, just removes the duplicate definition.

### CODE REVIEW

**Comment by jschloss-swift** [comment]
I signed it!

**Comment by jschloss-swift** [comment]
I signed it!

**Comment by gennadiycivil** [comment]
No CLA

**Comment by jschloss-swift** [comment]
OK, we got confirmation now that the CLA went through ~12PM today.

**Pull request merged**
