### PR TITLE
Generate import configs for other CMake projects to include

### PR DESCRIPTION
**Pull request by andreyvps**
for both Debug and Release builds by appending 'd' to the binary names
of the debug binaries.

### CODE REVIEW

**Comment by andreyvps** [comment]
I signed it!

**Comment by Knitschi** [comment]
I did something similar in the hunter package fork of google test here: https://github.com/hunter-packages/googletest

I used the functions `write_basic_package_version_file()`  and `configure_package_config_file()` from the `CMakePackageConfigHelpers` module instead of the 

```
install(EXPORT GtestTargets
  FILE GmockConfig.cmake
  NAMESPACE Gtest::
  DESTINATION cmake
)
```
function that you use. Do you know what the difference is? The [documentation of the CMakePackageConfigHelpers](https://cmake.org/cmake/help/latest/module /CMakePackageConfigHelpers.html) states that this approach yields relocateable packages because the Config.cmake file does not contain hardcoded pathes. Do you know if the package that is generated with your implementation is relocateable?

**Comment by gennadiycivil** [comment]
Conflicting files
googlemock/CMakeLists.txt
googletest/CMakeLists.txt

**Comment by gennadiycivil** [comment]
This PR is fairly old and with merge conflicts. At the same time looks potentially useful.
About to close, ping me otherwise

**Pull request closed without merging**
