### PR TITLE
Remove gtest VS2005 projects

### PR DESCRIPTION
**Pull request by KindDragon**
Depend on PR #1219

### CODE REVIEW

**Comment by gennadiycivil** [comment]
Question here:
Why dont we just delete these?  It is 2017, VS2005 is ancient history.

**Comment by KindDragon** [comment]
Ok, let's delete them

**Comment by gennadiycivil** [comment]
Awesome, would you mind doing the honors? Send me a PR to delete them or modify this one. ( Good thing we moved them to separate dir :)

**Comment by KindDragon** [comment]
Done

**Comment by KindDragon** [comment]
Please let's move forward with PR #1218. I can move each commit to separate PR if you want

**Pull request merged**
