### PR TITLE
Fixing version check

### LINKED ISSUE #2711: Build is broken for cmake 3.5
https://github.com/google/googletest/commit/23b2a3b1cf803999fb38175f6e9e038a4495c8a5 uses `VERSION_GREATER_EQUAL` which is not available in old versions of cmake. 
See more at https://github.com/glfw/glfw/issues/1584

### PR DESCRIPTION
**Pull request by massimiliano-leoni**
Closes #2711 with the fix proposed by olimasters [ https://github.com/google/googletest/issues/2711#issuecomment-586194922 ].

### CODE REVIEW

**Comment by massimiliano-leoni** [comment]
@googlebot I signed it!

**Comment by golikeri** [comment]
@googlebot when will this get merged?

**Comment by Mizux** [comment]
FYI fixed by cl/300766233 internally

**Comment by golikeri** [comment]
> FYI fixed by cl/300766233 internally

Thanks. When will this get merged to master?

**Comment by Mizux** [comment]
four days ago ?
https://github.com/google/googletest/commit/227faf41db5eec00fa2b316098a49771b2fb4ad8

**Comment by massimiliano-leoni** [comment]
I'll close this one then. I don't understand why it wasn't merged but the important thing is that the issue is fixed.

**Comment by golikeri** [comment]
Thanks. Yes it's merged now.

**Pull request closed without merging**
