### PR TITLE
Output information about skipped tests in xml output

### PR DESCRIPTION
**Pull request by mvoorsluys**
This pull request adds two things to the xml output:
- The number of skipped tests inside a suite. (As a property, like the number of failures)
- On skipped tests it also adds a skipped element to the xml.

I followed the JUnit description in https://llg.cubic.org/docs/junit/

### CODE REVIEW

**Comment by zhangxy988** [comment]
Please sign the CLA and make sure the tests pass.

**Comment by mvoorsluys** [comment]
@googlebot I signed it!

**Comment by mvoorsluys** [comment]
@googlebot I signed it!

**Comment by mvoorsluys** [comment]
@zhangxy988 The tests are passing, but the travis check remains pending. I don't know how I can solve this. The CLA has been resolved.

**Comment by mvoorsluys** [comment]
Fixes #1916

**Comment by CJ-Johnson** [comment]
Thank you, we have started internal review. Please don’t push any more changes into this PR as they might be overwritten. (313176466)

**Pull request merged**
