### PR TITLE
Merge pull request #2723 from JohanMabille/warnings

### PR DESCRIPTION
**Pull request by tuhin-52321**
Fixed warnings

### CODE REVIEW

**Comment by davidmerwin** [comment]
🧬

**Comment by davidmerwin** [comment]
🌹

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by davidmerwin** [comment]
💎

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: tuhin-52321 ***@***.***>
Sent: Tuesday, August 17, 2021 8:20:04 AM
To: google/googletest ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [google/googletest] Merge pull request #2723 from JohanMabille/warnings (#3528)


Fixed warnings

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/google/googletest/pull/3528

Commit Summary

  *   Merge pull request #2723 from JohanMabille/warnings

File Changes

Patch Links:

  *   https://github.com/google/googletest/pull/3528.patch
  *   https://github.com/google/googletest/pull/3528.diff

**Comment by tuhin-52321** [comment]
@googlebot I signed it!

**Pull request closed without merging**
