### PR TITLE
Enable building as a shared library (dll) on Windows with Bazel

### PR DESCRIPTION
**Pull request by samolisov**
While the google test library is being built as a shared library using Bazel,
so that there is a rule like

cc_test(
     name = "iterator_traits_test",
     linkstatic = 0,
     deps = ["@gtest//:gtest_main"],
     ...
)

in a BUILD file, the following error appears on Windows:

INFO: Found 1 test target...
ERROR: C:/../external/gtest/BUILD.bazel:55:1: output 'external/gtest/gtest.if.lib' was not created
ERROR: C:/../external/gtest/BUILD.bazel:55:1: not all outputs were created or valid
Target //test:iterator_traits_test failed to build

The reason is a missing "win_def_file" attribute of the "gtest" and
"gtest_main" rules in the BUILD.bazel inside the google test library
package.

The "windows_export_all_symbols" feature is added to the rules, this
feature forces Bazel to export all symbols from the google test library
to linker. I believe exporting all symbols from a testing library makes
no problem for the application from a point of view on encapsulation.

Signed-off-by: Pavel Samolysov <samolisov@gmail.com>

### CODE REVIEW

**Comment by gennadiycivil** [comment]
@samolisov we have CI setup and working without errors on Windows - see [appveyor builds](https://ci.appveyor.com/project/GoogleTestAppVeyor/googletest/builds/21559186).
While I am not disputing your changes, I think the problem may be local for you.

**Comment by samolisov** [comment]
@gennadiycivil Thank you for the response. Do I right understand, I should change `appveyor.yml` and put there a bazel-build?

**Comment by gennadiycivil** [comment]
ping

**Comment by samolisov** [comment]
@gennadiycivil sorry for the delay. Unfortunately, I'm not an appveyor 'guru' and it took time to configure a build with Bazel on that platform. I get it working now but appveyor downloads Bazel for every build (It can be incorrect but I see it on the builds related to this PR). Maybe someone, who is more competent with appveyor, is going to install Bazel on the platform once. Anyway, there is a proof of building googletest using Bazel and run it on Windows being dynamic linked with a test code.

This job: https://ci.appveyor.com/project/GoogleTestAppVeyor/googletest/builds/21794281/job/2tvmmqdefo8f1fy0 shows what happens when there is not a 
```bzl
    features = select({
        ":windows": ["windows_export_all_symbols"],
        "//conditions:default": [],
    })
```
in the library definition within the `BUILD.bazel` file:

```
ERROR: C:/projects/googletest/BUILD.bazel:124:1: output 'gtest_sample_lib.if.lib' was not created
ERROR: C:/projects/googletest/BUILD.bazel:124:1: not all outputs were created or valid
Target //:gtest_samples failed to build
```

If you want, I can brake this PR into two - one for Bazel on appveyor and one for exporting everything from the `gtest.dll` library. Shall I?

P.S. Unfortunately, if the *googlemock* is used in tests, the library must be linked statically or some symbols won't be found by the linker but this is another story.

P.S.S. Could the changes to the `BUILD.bazel' file be back ported into 1.8.1?

**Pull request merged**
