### PR TITLE
Remove a custom implementation of std::iterator_traits

### PR DESCRIPTION
**Pull request by kuzkry**
#2392

### CODE REVIEW

**Comment by asoffer** [comment]
263420445

**Comment by EricWF** [comment]
LGTM.

I'll leave @asoffer in charge of merging this, since he's doing the hard work of testing it internally.

**Comment by gennadiycivil** [comment]
Note that this has been merged https://github.com/google/googletest/pull/2398 however there is a warning that some commits may have not been migrated.

This commit has the details https://github.com/google/googletest/commit/565f1b848215b77c3732bca345fe76a0431d8b34

Please make sure to NOT add more changes once we 

Pull Request https://github.com/google/googletest/pull/2398 has more changes after e2c06aa2497e330bab1c1a03d02f7c5096eb5b0b (PR HEAD is a9945a16f8069c8b216b9a2fd6d8879e8bef675b). Not all changes might be migrated

**Comment by kuzkry** [comment]
@gennadiycivil I know exactly what you mean. When you are on a merge commit and you call `git merge` (because you wanna merge to an even newer commit), git may just combine two merge commits into one.
So don't worry, I checked it and everything is as it should be. Thanks the warning and the merge!

**Comment by kuzkry** [comment]
Merged by 565f1b84.

**Pull request closed without merging**
