### PR TITLE
Iterate untyped expectations vector back without reverse_iterator to workaround a bug  in VS 2019 16.4

### PR DESCRIPTION
**Pull request by macqm**
Workaround fix for #2628 
Using range based for-loop generates code that doesn't crash and the bug does not reproduce.

### CODE REVIEW

**Comment by ThadHouse** [comment]
This is failing testing because the original iterator is a reverse iterator, whereas range for goes forward. Below is code using forward iterators, but going backward.


```
    for (typename UntypedExpectations::const_iterator it =
             untyped_expectations_.end();
         it != untyped_expectations_.begin(); --it) {
      typename UntypedExpectations::const_iterator tmp = it;
      --tmp;
      TypedExpectation<F>* const exp =
          static_cast<TypedExpectation<F>*>(tmp->get());
      if (exp->ShouldHandleArguments(args)) {
        return exp;
      }
    }
```

**Comment by macqm** [comment]
Thanks @ThadHouse, I pushed a commit with your suggestion.

**Comment by gennadiycivil** [comment]
@macqm Thank you for this. I am not sure if we should be changing code to work around various bugs that various compilers may have.

**Comment by gennadiycivil** [comment]
The codebase is correct C++ . If a compiler has an issue we should we working with the compiler to fix it.

**Pull request closed without merging**
