### PR TITLE
Feat: add esp8266 support

### LINKED ISSUE #2433: Add support for ESP8266
Now that we have support for ESP32, it would be nice to support the ESP8266 platform.

### PR DESCRIPTION
**Pull request by ciband**
This change adds support for the ESP8266 platform.  It also refines the support for these Arudino platforms, attempting to align with the GTEST_OS_* pattern.

This resolves #2433 .

### CODE REVIEW

**Comment by kuzkry** [comment]
Then you may wanna prepend "WIP:" to your pull request name. This is the standard way of tagging drafts.

**Comment by ciband** [comment]
Will do. Thank you.

**Comment by ciband** [comment]
Last commit pushed by me using a public token.  I assume that was the problem.

@googlebot I fixed it.

**Comment by ciband** [comment]
I think this is ready for review.

**Comment by ciband** [comment]
I am not sure how to clear the cla:no tag.  I have pushed all the commits to this patch and my account has signed the agreement.

Is there anything else I need to do in order for this patch to be considered?

Thank you.

**Comment by kuzkry** [comment]
> I am not sure how to clear the cla:no tag. I have pushed all the commits to this patch and my account has signed the agreement.
> 
> Is there anything else I need to do in order for this patch to be considered?
> 
> Thank you.

First things first, let's fix your history a bit:
```
git checkout feat/add_esp8266_support
git branch tmp # this is a "backup" branch
git rebase --onto fdd6a1dc HEAD~2 feat/add_esp8266_support
git push -f origin feat/add_esp8266_support
```
This will get rid of your merge commits and will rebase you onto the actual google:master which doesn't match your master. fdd6a1dc is the commit I noticed you wanted to be on. After this process you should have 2 commits.

Then, one of these two commits is authored by chrisjohnsonmail@gmail.com, second by chris.a.johnson@garmin.com. It's fine if you call either:
`git commit --amend --author="Chris Johnson <chrisjohnsonmail@gmail.com>"`
 or
`git commit --amend --author="Chris Johnson <chris.a.johnson@garmin.com>"`
while being on top of the wrong commit.

**Comment by ciband** [comment]
@kuzkry 
Thanks for the help and advice.  I'll get these changes in.

**Comment by ciband** [comment]
Ok, I think I have the commits and authoring correct now.  Please let me know if I need to do anything else.

@kuzkry Thanks for the help.

**Comment by kuzkry** [comment]
Heh, I don't know if I really helped, I can see a series of googlebot complains :D Anyway, I'm glad you managed to sort it out :sunglasses:

**Comment by ciband** [comment]
Looks like Travis CI failed due to some internal CI issue.  I would expect a re-run of CI to pass the builds.  It doesn't look like I have permissions to do so.

**Comment by kuzkry** [comment]
If you want to retrigger verification there's a handy trick. Try to close and reopen this pull request. You're welcome! :wink:

**Comment by ciband** [comment]
Closed and opened to retrigger CI

**Comment by ciband** [comment]
CI seems unstable as different platforms fail on different builds.  The most recent seem to be when trying to install system packages before the build.

I would think this change is ok.  The PIO builds pass and that is the primary code path this is modifying.

Are there any changes that any reviewers would like to see?

**Comment by ciband** [comment]
CI seems good now.  Would there happen to be a rough time frame as to when this might be merged?  I've got some additional support in the Arduino world I would like to submit but this needs to go in first.

Thank you for your consideration.

**Comment by ciband** [comment]
I have messed up the history.  My apologies.  I will close this request and just make a new one.

**Pull request closed without merging**
