### PR TITLE
Fixed MSVC warnings

### PR DESCRIPTION
**Pull request by krizalys**
This PR fixes compilation warnings in recent versions of Visual Studio.

### CODE REVIEW

**Comment by KindDragon** [comment]
This already fixed in PR #811

**Comment by krizalys** [comment]
@BillyDonahue are you considering reviewing/merging either this or #811?

**Comment by krizalys** [comment]
Perhaps @BillyDonahue would like to give this a review?

**Comment by KindDragon** [comment]
Can be closed. PR #1218 fixed this

**Comment by krizalys** [comment]
Already fixed in #1218.

**Pull request closed without merging**
