### PR TITLE
Travis CI: The sudo: tag is now deprecated in Travis CI

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by gennadiycivil** [comment]
@cclauss Thank you for this change, could you please link corresponding Travis docs.

**Comment by cclauss** [comment]
From 2018: "[___Timeline - it’s happening fast!  [...]  Soon we will run all projects on the virtual-machine-based infrastructure, the sudo keyword will be fully deprecated.___](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration)"

**Comment by cclauss** [comment]
@gennadiycivil Why was this PR reverted?

**Comment by gennadiycivil** [comment]
@cclauss probably sync mistake.

**Pull request merged**
