### PR TITLE
complexity of the function IsValidUTF8 #2779

### PR DESCRIPTION
**Pull request by desosa-9**
This change addresses issue #2779. The complexity of the function IsValidUTF8 is decreased, by distilling the conditions of the if-statements into separate functions.

### CODE REVIEW

**Comment by desosa-9** [comment]
@googlebot I signed it!

**Comment by asoffer** [comment]
CLA doesn't look signed. Try again?

**Comment by desosa-9** [comment]
@googlebot I signed it!

**Comment by desosa-9** [comment]
I've signed the CLA with a google account, and I assigned that google account to this github account. Afterwards I've recreated the pull request but the CLA check still fails unfortunately.

**Pull request closed without merging**
