### PR TITLE
Fix compilation error when both gtest and <tr1/tuple> are included (GTEST_LANG_CXX11=1)

### PR DESCRIPTION
**Pull request by oliora**

### CODE REVIEW

**Comment by gennadiycivil** [comment]
Doing some cleanup and closing outstanding PRs that 
1) don't have all checks OK
2) have been around for a while with no activity

**Comment by oliora** [comment]
If you can tell me what checks are failed then I will fix it.

**Comment by gennadiycivil** [comment]
@oliora When you submit a PR please take a look at TravisCI and AppVeyor. Both should pass. 
Thank you

**Comment by oliora** [comment]
At the moment I've submitted the PR The the CI had been broken for some platforms (I don't remember details now). I'll resubmit the PR.

**Pull request closed without merging**
