### PR TITLE
Remove deprecated SetArgumentPointee

### PR DESCRIPTION
**Pull request by kuzkry**

### CODE REVIEW

**Comment by asoffer** [comment]
Unfortunately there are still thousands of uses inside Google. We'll see how quickly I can get rid of them.

**Comment by asoffer** [comment]
We're almost done cleaning up Google's codebase. Maybe another week or so before we can pull this in. Thanks for your patience.

**Comment by kuzkry** [comment]
Rebased to resolve the merge conflict.

**Comment by asoffer** [comment]
After some discussion internally, there is not consensus on removing this. The consensus for the time being is that it would break external users without providing significant benefit. We may revisit this in the future.

**Pull request closed without merging**
