### PR TITLE
Fix Clang's `-Wdeprecated-copy` warnings in C++20

### LINKED ISSUE #1305: Clang warning with -Wdeprecated in MATCHER_P generated matchers
As reported by @francoechea in google/googlemock#211 , in the expansion of `MATCHER_P` there's a -Wdeprecated warning by Clang because the class defines a copy assignment operator (to make it private), but does not define a copy constructor, and implicit copy constructor generation is deprecated in such cases in C++11:

     definition of implicit copy constructor for 'FooMatcherP2<double, double>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated]

When I bumped into this myself, I tried simply adding a copy constructor like:

    name##MatcherP(const name##MatcherP &other) : p0(other.p0) {\
    }\

to the `MATCHER_P` macro I was using, and it seemed to work.

Should perhaps whatever code generates these `MATCHER_P` macros make sure they have explicitly defined copy constructors like this?

### PR DESCRIPTION
**Pull request by Quuxplusone**
Fixes #1305.
(I think. Hopefully you've got a buildbot that will tell me if this breaks something.)

### CODE REVIEW

**Comment by Quuxplusone** [comment]
@googlebot I signed it!

**Comment by Quuxplusone** [comment]
@gennadiycivil: Please commit this patch.

@aardappel: Here's the GTest/GMock counterpart to https://github.com/google/flatbuffers/pull/5829 . Do you have any sway over here?

**Comment by aardappel** [comment]
@Quuxplusone I'm afraid I don't :)

**Comment by Quuxplusone** [comment]
> We don't want any macros, so please replace `GTEST_DISALLOW_ASSIGN_BUT_DEFAULT_COPY_` by spelling it out. Thanks!

@zhangxy988: That's awesome news. Would you mind if I submitted another PR to remove these macros _first_ (i.e. manually preprocess these macros throughout the codebase, without changing any behavior), and then submitted a followup PR with _just_ localized fixes for the Clang C++20 warnings? I'll work on that tonight and add you as a reviewer on the PR(s).

**Comment by Quuxplusone** [comment]
@zhangxy988: I've opened #2772 and #2773. Once those are both in, then I'll submit a PR for the macro removal and to add `-Wdeprecated` to the Travis build. (I just accidentally opened that as #2774, but I don't think it's worth looking at #2774 until #2772 and #2773 are both in, so I closed #2774 for now.)

**Comment by Quuxplusone** [comment]
Abandoned in favor of #2815.

**Pull request closed without merging**
