### PR TITLE
Fix typed- and type-parameterized test clang warnings

### PR DESCRIPTION
**Pull request by kuzkry**
This refers to [issue #2271](https://github.com/google/googletest/issues/2271)

### CODE REVIEW

**Comment by kuzkry** [comment]
Please let me know if that's fine, so I could read and sign the whole CLA document.

**Comment by kuzkry** [comment]
I have signed the CLA.

**Comment by muttleyxd** [comment]
This would be very nice to have

**Comment by gennadiycivil** [comment]
Thank your for this contribution. Could you please elaborate and provide more information on exactly the issue / problems this is trying to address.
What is the before/after effect this would create and how is this beneficial?

**Comment by gennadiycivil** [comment]
260558200

**Comment by kuzkry** [comment]
Sure, let me explain (commit-wise):
first 2 commits are dumb improvements I found here and there while preparing this PR
1st commit - I noticed documentation given in googletest/docs/advanced.md does not match the corresponding section in googletest/include/gtest/gtest-typed-test.h
2nd commit - names of unused parameters are normally left out
3rd commit - currently GTest macros of typed tests do not conform with C++ standard (as I explained in the body of the commit message, please have a look) because when using a variadic parameter in a macro, it should be always given a lt least one parameter. Clang rightfully complains.
So:
```c++
#define MY_BEAUTIFUL_MACRO(foo, ...) <some code>

MY_BEAUTIFUL_MACRO("i'm", "five"); // Good
MY_BEAUTIFUL_MACRO("I'm"); // Bad```

Hope it answers your questions.

Btw. what's the meaning of 260558200? :D

**Comment by gennadiycivil** [comment]
@kuzkry Thank you for this. Could you please just leave one change in this PR, whichever one you think is most important. This way it would be easier to follow and review. Thank you again

**Comment by kuzkry** [comment]
> @kuzkry Thank you for this. Could you please just leave one change in this PR, whichever one you think is most important. This way it would be easier to follow and review. Thank you again
> 
> Oh, and dont pay attention to 260558200 , just some internal housekeeping

@gennadiycivil, I've moved the unimportant stuff to #2358.
So now, quick update what this PR is all about:
>     * 3rd commit - currently GTest macros of typed tests do not conform to the C++ standard (as I explained in the body of the commit message, please have a look [here](https://github.com/google/googletest/pull/2316/commits/42ab7528a31ea19817a30c10f39e2cbb66cfc2d6)) because when using a variadic parameter in a macro, it should be always given a lt least one parameter. Clang rightfully complains.
>       So:
> 
> 
> ```c++
> #define MY_BEAUTIFUL_MACRO(foo, ...) <some code>
> 
> MY_BEAUTIFUL_MACRO("i'm", "five"); // Good
> MY_BEAUTIFUL_MACRO("i'm"); // Bad
> ```

**Comment by gennadiycivil** [comment]
@kuzkry Looks like you have 2 new macros here
INSTANTIATE_TYPED_TEST_SUITE_CUSTOM_NAME_GENERATOR_P and INSTANTIATE_TYPED_TEST_SUITE_CUSTOM_NAME_GENERATOR_P. 
We have a very high bar on introducing new macros , we actively discourage new macros.

**Comment by kuzkry** [comment]
> @kuzkry Looks like you have 2 new macros here
> INSTANTIATE_TYPED_TEST_SUITE_CUSTOM_NAME_GENERATOR_P and INSTANTIATE_TYPED_TEST_SUITE_CUSTOM_NAME_GENERATOR_P.
> We have a very high bar on introducing new macros , we actively discourage new macros.

@gennadiycivil Yes, I've added 2 new macros here because currently our existing macros, i.e. TYPED_TEST_SUITE and INSTANTIATE_TYPED_TEST_SUITE_P, are nice and such but they are not compliant with any of C++ standards. The sole reason they work are compiler extensions. Current code [will become perfectly legal with C++20](https://en.cppreference.com/w/cpp/preprocessor/replace)  but this project is a long way from imposing this as a requirement.
I consider my changes as a trade-off between:
a) sticking to what we have with less macros, though relying on cleverness of compilers
b) doing it like suggested in this pull request with more macros, though made correct and portable

**Comment by gennadiycivil** [comment]
From what I can see you are using -Wall and -Wextra. As previously discussed, (https://github.com/google/googletest/issues/2069#issuecomment-457362864) we are not willing to support these in their entirety.

**Comment by gennadiycivil** [comment]
I ll close this now but please come back if you can come up with different solution that does not require new macros.
Thank you again

**Pull request closed without merging**
