### PR TITLE
Detect Fuchsia, and set GTEST_HAS_PTHREAD on GTEST_OS_FUCHSIA

### PR DESCRIPTION
**Pull request by sgraham**
Detect the Fuchsia OS https://fuchsia.googlesource.com/docs/+/master/README.md based on the `__Fuchsia__` define being set. It's somewhat POSIX-y and has pthreads available, so ensure pthreads is on so that the broken no-op Mutex isn't silently used.

This is an upstream of internal 167008015.

### CODE REVIEW

**Comment by gennadiycivil** [comment]
Please provide description for the rest of us. Explain what this is doing and more importantly why it is doing it. Thank you

**Comment by gennadiycivil** [comment]
Is this an upsreaming of internal work?

**Comment by sgraham** [comment]
Sorry, not familiar with github's UI. Updated the description above.

**Comment by gennadiycivil** [comment]
Thank you for more information :-) could you please let me know if this is brand new or is this an upstream of an internal CL?

**Comment by sgraham** [comment]
This is new code.

**Comment by sgraham** [comment]
This is now an upstreaming (slightly rebased due to NETBSD change that doesn't seem to be internal yet?) of internal CL 167008015.

**Comment by gennadiycivil** [comment]
This is duplicate now, I already merged https://github.com/google/googletest/pull/1237

**Pull request merged**
