### PR TITLE
[msys] pass big object file option to assembler for target gmock-matchers_test

### PR DESCRIPTION
**Pull request by matlo607**
fix issue #1841

### CODE REVIEW

**Comment by matlo607** [comment]
Hello @gennadiycivil,
The reason for the failing build is the below (I guess some connectivity issues):
```
apt-get install failed
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install g++-4.9 clang-3.9" failed and exited with 100 during .
```
Should I update the date of the commit to force a new build ?
Or can you still merge if your review is OK ?

**Comment by KindDragon** [comment]
Maybe better modify script here https://github.com/google/googletest/blob/master/googletest/cmake/internal_utils.cmake#L207-L210

**Comment by matlo607** [comment]
Hello @KindDragon,
As I said in the issue #1841,
> Passing the option -mbig-obj to gas through GCC with -Wa allows GCC to build the object file but in return, **highly increases the build time of the target** (I would say by **2 or 3 minutes** depending on the CPU of your machine).

There are around 60 unit tests with both gtest and gmock. I don't want to specify this flag globally because the build time would take 60 * 3 minutes = 3 hours !
I don't know the reason why the build time is so much increased. I did some research but could not find anything relevant.
For now, I want to have a minimal impact and specify it only for the needed target.

**Comment by gennadiycivil** [comment]
@matlo607 I restarted failed travis build

**Pull request merged**
