### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by ghatwala**
Adding power support

### CODE REVIEW

**Comment by gennadiycivil** [comment]
CI failed 
https://travis-ci.org/google/googletest/jobs/550803837

**Comment by gennadiycivil** [comment]
Looks like Travis does not support this: "N: Skipping acquire of configured file 'main/binary-ppc64el/Packages' as repository 'http://apt.llvm.org/precise llvm-toolchain-precise-3.9 InRelease' doesn't support architecture 'ppc64el'"

**Comment by ghatwala** [comment]
@gennadiycivil  - saw  a tarball here - releases.llvm.org/7.0.1/clang+llvm-7.0.1-powerpc64le-unknown-unknown.tar.xz

**Comment by gennadiycivil** [comment]
@ghatwala Sorry I am not sure what you mean. If you need googletest CI to support this platform a complete PR that solves this problem is expected.

**Comment by ghatwala** [comment]
Sure will check this part , what additional changes need to get in here to get PR job - Thanks for the response !!!

**Comment by gennadiycivil** [comment]
No CLA, closing

**Pull request closed without merging**
