### PR TITLE
Add `cxx_strict_flags` for clang to match FreeBSD's WARNS flags

### PR DESCRIPTION
**Pull request by ngie-eign**
Signed-off-by: Enji Cooper <yaneurabeya@gmail.com>

### CODE REVIEW

**Comment by ngie-eign** [comment]
This PR requires #2123 and #2125.

**Comment by ngie-eign** [comment]
@gennadiycivil: ping?

**Comment by gennadiycivil** [comment]
@ngie-eign There is a number of flags ... what would it take to "just fix the code?"
Thanks again for all this work!
G

**Comment by gennadiycivil** [comment]
@ngie-eign also if you could please explain in greater details these flags ( for example I am not familiar with Wformat-y2k

**Comment by ngie-eign** [comment]
> @ngie-eign There is a number of flags ... what would it take to "just fix the code?"
> Thanks again for all this work!
> G

The additional flags are to ensure that the code doesn't regress (as much) between FreeBSD and Linux/OSX.

> @ngie-eign also if you could please explain in greater details these flags ( for example I am not familiar with Wformat-y2k

These flags are probably set as a precursor of a larger -Wformat set. Per the `gcc` manpage:
```
           -Wformat=2
               Enable -Wformat plus additional format checks.  Currently
               equivalent to -Wformat -Wformat-nonliteral -Wformat-security
               -Wformat-y2k.
...
           -Wformat-y2k
               If -Wformat is specified, also warn about "strftime" formats
               that may yield only a two-digit year.
```

This is protecting against `%g`/`%y` [on FreeBSD at least]:
```
     %g    is replaced by the same year as in “%G”, but as a decimal number
           without century (00-99).
...
     %y    is replaced by the year without century as a decimal number
           (00-99).
```
They want to ensure that double digit years aren't provided, resulting in hard to decipher dates when centuries may vary, as some dates might be 20th century values and some might be 21st century values (or later). Example `00` can be 1800, 1900, 2000, 2100, etc.

**Comment by gennadiycivil** [comment]
Hmm. So I just built googletest with bazel build --cxxopt=-Wformat googletest/... and it worked without any issues.
Then I tried bazel build --cxxopt=-Wformat-y2k googletest/... also worked just fine.
Then I did bazel build --cxxopt=-Wformat=2 googletest/... also worked just fine.

Not sure why we are doing -Wno-format-y2k when in fact it does not seem to create an issue.... could you please advise?

**Comment by ngie-eign** [comment]
> Hmm. So I just built googletest with bazel build --cxxopt=-Wformat googletest/... and it worked without any issues.
> Then I tried bazel build --cxxopt=-Wformat-y2k googletest/... also worked just fine.
> Then I did bazel build --cxxopt=-Wformat=2 googletest/... also worked just fine.
> 
> Not sure why we are doing -Wno-format-y2k when in fact it does not seem to create an issue.... could you please advise?

I was mimicking FreeBSD's options, but (as you suggested), this flag isn't necessary. I'll remove it now and force push the change.

**Comment by ngie-eign** [comment]
I just removed `-Wno-format-y2k`.

**Comment by gennadiycivil** [comment]
Merged

**Pull request closed without merging**
