### PR TITLE
Replaced template arguments A0, A10 with TArg0..10

### PR DESCRIPTION
**Pull request by Aralox**
https://github.com/google/googletest/issues/2135

### CODE REVIEW

**Comment by gennadiycivil** [comment]
No CLA

**Comment by Aralox** [comment]
Still working on it, I'll let you know when I've sorted it out with my company. Thanks

**Comment by gennadiycivil** [comment]
@Aralox just to let you know, we had an internal discussion and yes we would be OK with this change because it would be useful for your work.
Just please make sure to change the .pump files and re-gen, dont change this directly.  And work out the CLA of course 
thanks again

**Comment by PravinPrameKumar** [comment]
Thank you, I'm glad to hear that :). I've changed gmock-generated-actions.h.pump and regenerated the header file. CLA still in progress, I'll message back when its good to go.

**Comment by gennadiycivil** [comment]
Ping

**Comment by PravinPrameKumar** [comment]
Still in progress! ☺️

**Comment by gennadiycivil** [comment]
I will close this for now, please come back when ready

**Comment by PravinPrameKumar** [comment]
Sure, no worries, will do.

**Comment by Aralox** [comment]
Hi @gennadiycivil, I've decided to re-do this PR for hacktoberfest :) (https://hacktoberfest.digitalocean.com/hacktoberfest-update)
I've submitted it under my own name this time, and have accepted the CLA.
My changes are much simpler this time, they only involve gmock-nice-strict.h, because of the wonderful work done last year to use variadic templates in gmock-generated-actions.h.

**Comment by Aralox** [comment]
Reopened as https://github.com/google/googletest/pull/3042
(much simpler)

**Review by toto199 — COMMENTED** [review]
Toto

**Pull request closed without merging**
