### PR TITLE
Allow macros inside of parametrized test names.

### PR DESCRIPTION
**Pull request by sheepmaster**

### CODE REVIEW

**Comment by sheepmaster** [comment]
Copied over from https://github.com/google/googletest/pull/706, which didn't list the CLA as accepted for some reason.

**Comment by sheepmaster** [comment]
@gennadiycivil PTAL, thanks!

**Comment by sheepmaster** [comment]
@gennadiycivil Ping?

**Comment by gennadiycivil** [comment]
Thank you for your contribution. 
Could you please provide explanation _why_ allowing macros inside of parametrized test names is needed.
Not clear what problem we are trying to solve?
Thank you

**Comment by sheepmaster** [comment]
A common pattern in Chromium code to conditionally disable tests (e.g. on certain platforms) is to use a macro to expand the test name to `DISABLED_...` when the condition is met. For example:
```
  #if defined(OS_MACOSX)
  #define MAYBE(X) DISABLED_X
  #else
  #define MAYBE(X) X
  #endif
  TEST(FooTest, MAYBE(BAR)) { ... }
```

That works with `TEST` or `TEST_F`, but not with `TEST_P`, but that is not obvious. Now, adding to that the fact that the most common use for disabling tests is to get the tree green again, trying to disable a parametrized test in this way would instead cause a compile failure. This PR just aligns the behavior for TEST_P with TEST_F and TEST.

**Comment by gennadiycivil** [comment]
Looks sane to me... could you please do internal CL first? ( As per [DevGuide](https://github.com/google/googletest/blob/7f8fefabedf2965980585be8c2bff97458f28e0b/googletest/docs/DevGuide.md#submitting-patches))

**Comment by gennadiycivil** [comment]
ping

**Comment by sheepmaster** [comment]
Internal CL is up at cr/169519470.

**Pull request merged**
