### PR TITLE
Misc. typos found via downstream projects

### PR DESCRIPTION
**Pull request by luzpaz**
Found using `codespell -q 3 -I ../googletest-word-whitelist.txt`

### CODE REVIEW

**Comment by luzpaz** [comment]
Tried signing the CLA but it wants a google account. I'd rather not associate the CLA to a google account. Is there any other way to sign the CLA ?

**Comment by gennadiycivil** [comment]
@luzpaz Thank you for your contribution. The changes are useful, but I don't see a CLA for you.

**Comment by luzpaz** [comment]
@gennadiycivil https://github.com/google/googletest/pull/1818#issuecomment-419710984

**Comment by gennadiycivil** [comment]
@luzpaz I don't know if any other way, sorry. Please let me know what you would like to do.

**Comment by luzpaz** [comment]
@gennadiycivil i can close this PR, you could patch it under your name in to the source and merge it. I give up any rights to it.

**Comment by gennadiycivil** [comment]
@luzpaz thank you

**Comment by luzpaz** [comment]
Closing

**Pull request closed without merging**
